### ISSUE TITLE
V2 - add more descriptive error messages when Tree Api fails

### ISSUE THREAD

**Issue by kapakos** [TreeMama/iSeaTree-React-Prototype#100]
When clicking on 'Calculate Tree Benefits' the API might return an error message for various reasons. Currently we always show the default message: "The USFS iTree API was not able to calculate the Tree Benefits for this species."

It might make sense to show a more descriptive message.

**Comment by TreeMama** [comment]
@JonathanKoerber - it was pointed out for the 'generic' message - that it should actually read:

"The USFS iTree API was not able to calculate the Tree Benefits for this **tree**."

can you maybe fix this one word?>

**Comment by TreeMama** [comment]
fixed - thanks @jyang81
