### ISSUE TITLE
V2.1 - reformat the profile screen

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#101]
Based on AnMaree's excellent design - (and our current utter lack of design effort on the profile screen) - I was wondering if we could take a stab at reformatting this a bit before the V2 release?

This image isn't exactly what we need....but it is darn close.

Notes about this image:

We still need a place to put our 'For Help' link...somewhere.... (note: we can probably get rid of the 'For Map').  Maybe (for now) instead of all the icons on the right of the screen - just include ONE "?" icon that goes to the "For Help" link?

Use this for the icons:

trees: https://fontawesome.com/icons/tree?style=solid\
for the badges 'earned' graphic: https://fontawesome.com/icons/graduation-cap?style=solid

https://drive.google.com/drive/u/1/folders/1Sla8AUaH1mANN7KrrUiWo6Nz4v9sFZnZ

![profile](https://user-images.githubusercontent.com/62637055/105249795-84869300-5b2d-11eb-8664-eb2808dd5e7a.JPG)

**Comment by JonathanKoerber** [comment]
I could take this one on. Is the above image how the screen would like to look? Also, do we have the icons? Will that NavBar carry over through out the app?

**Comment by TreeMama** [comment]
@JonathanKoerber - I'm working on the icons now....ignore the nav bar changes in the graphic for now. They are V3 items. V2 would be the screen items for the profile page....

**Comment by TreeMama** [comment]
Punting this to V2.1. It's a high priority...but will not block the V2 release.
