### ISSUE TITLE
V2 - Add 'CO2 stored to date' to the Tree Benefits Calculator

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#105]
In the Tree Benefits Calculator we should report 2 more values for CO2. They are listed in the itree api as :

<CarbonDioxideStorageUnit></CarbonDioxideStorageUnit> (lbs)

<CarbonDioxideStorageValue></CarbonDioxideStorageValue> ($)

Unlike the currently reported CO2 values (which are annual totals) this is a total to DATE. 

Add this underneath the "Carbon Dioxide (CO2) Sequestered (Yearly)" report as:

"Total Carbon Dioxide (CO2) Storage (To Date)"  : <CarbonDioxideStorageUnit></CarbonDioxideStorageUnit> lbs

 "Total Carbon Dioxide (CO2) Storage Value (To Date)" : $<CarbonDioxideStorageValue></CarbonDioxideStorageValue>

**Comment by TreeMama** [comment]
Also - we need to return ALL these values to the backend firebase (like we are doing with CLE etc)...I will update git issue #94 to emphasize this...

https://github.com/TreeMama/iSeaTree-React-Prototype/issues/94

**Comment by jyang81** [comment]
I finally got this working. The Carbon data isn't nested under the Benefit section, so it wasn't being converted to JSON. It took a lot of debugging, but I figured it out. I also put "Annual" and "To Date" headers and separated the data accordingly.
![IMG_0583](https://user-images.githubusercontent.com/44694525/103988569-393eae80-5143-11eb-9fa4-c9d42113a9ef.PNG)

**Comment by jyang81** [comment]
This issue can be closed if you are satisfied with the above.

**Comment by TreeMama** [comment]
Excellent stuff Thanks @jyang81
