### ISSUE TITLE
V2 - Add "Yearly" to the Yearly iTree API values

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#106]
we need to indicate that the H2O/CO2 removed/Air Quality improved we are reporting now are YEARLY totals...

they should read as this:

"Carbon Dioxide (CO2) Sequestered Value (Yearly)"
"Carbon Dioxide (CO2) Sequestered (Yearly)" 
"Storm Water Runoff Avoided Value (Yearly)"
"Storm Water Runoff Avoided Volume (Yearly)"
"Air Pollution Removed Value (Yearly)"
"Air Pollution Removed Volume (Yearly)"

**Comment by jyang81** [comment]
I added "(Yearly)" to the titles, but I couldn't figure out how to get the correct values for the Air Pollution items, so I did not add them.

**Comment by halmueller** [comment]
Reopening because the Air Pollution values aren't being retrieved yet. See earlier comments.

**Comment by jyang81** [comment]
Got it. I shouldn't have auto-closed the issue. If someone could help with the Air Pollution part, I'd love to complete the task.

**Comment by TreeMama** [comment]
Hi @jyang81 - for Air Pollution (which hasn't currently been added) the metric is this:

For "Air Pollution Removed Value (Yearly)" sum (and use the sum as the # in the reported total):

<CORemovedValue></CORemovedValue>
<NO2RemovedValue></NO2RemovedValue>
<SO2RemovedValue></SO2RemovedValue>
<O3RemovedValue></O3RemovedValue>
<PM25RemovedValue></PM25RemovedValue>

For "Air Pollution Removed Volume (Yearly)" sum:

<CORemoved></CORemoved>
<NO2Removed></NO2Removed>
<SO2Removed></SO2Removed>
<O3Removed></O3Removed>
<PM25Removed></PM25Removed>

**Comment by jyang81** [comment]
@TreeMama Thanks for the info. I was able to figure it out and committed a PR.

**Comment by jyang81** [comment]
Making changes per @TreeMama 's suggestion:
> "Annual:" header (in bold) above everything BUT CO2 to date - and then a header that says 'To Date:' above the CO2 'to Date' values
