### ISSUE TITLE
V2 (Calculate Tree Benefits) - Text Formatting & Add Location info from API

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#118]
We need to see if we can fit all the info in 1 mobile view (scrolling should still be an option - but we should give the users the power to take a screen capture of the info if they want).

To Do:

1) Try to make more space available in the screen view by decreasing the green 'message' box ...and the font size of the error / info reported there (maybe 2 pts lower then ALL the other text on screen).

2) Add 'Nation' 'State' 'City' from the iTree API (under the <Location></Location> tag). See image below (**After talking to @JonathanKoerber we WILL not be including 'County'**).

3) In cases where the word 'Carbon Dioxide' occurs...delete it and just have CO2. For example: "Carbon Dioxide (CO2) Sequestered Value" should change to "CO2 Sequestered Value".

![textedits](https://user-images.githubusercontent.com/62637055/104057282-bbac8a00-51a6-11eb-9dce-985451bb213a.jpg)

**Comment by TreeMama** [comment]
@JonathanKoerber @jyang81 - this is the highest priority to get done (outside of the maps items...which are already in flight). 

As discussed with @JonathanKoerber - we are going to skip putting "County" in - but DO put in nation, state, and city.

**Comment by jyang81** [comment]
Here's a screenshot of the work I did. I was thinking of getting rid of the light green box altogether, but wanted to let you see it first and then decide. 

<img src='https://user-images.githubusercontent.com/44694525/105613763-880e5a00-5d79-11eb-90f9-b67a526221a4.PNG' width=300>

**Comment by halmueller** [comment]
Is the gray text on green easily readable on device in bright sunlight?

**Comment by TreeMama** [comment]
@jyang81 yeah, I think I'd agree with hal...the green text on green box might be visually hard to read. Can we keep the text black in the green box?

I also think we don't need 'Species:' and 'Location:'...but you can decide on that. 

It looks really good thanks for this!

**Comment by jyang81** [comment]
I didn't check it outside, but it could be a little hard to see. It's green text, but pretty much equivalent to gray. The text is clearer on my actual phone than the screenshot above, but after looking at it again, I agree that the contrast ratio isn't high enough. I will either revert the text to black or remove the green background.

@TreeMama I'll remove the Species and Location titles.

**Comment by jyang81** [comment]
Screencaps of my edits below:

<img src='https://user-images.githubusercontent.com/44694525/105623697-6d1b0480-5dd0-11eb-9439-69db2d328f7b.PNG' width=300> . <img src='https://user-images.githubusercontent.com/44694525/105623698-70ae8b80-5dd0-11eb-938b-b8a1987eb74f.PNG' width=300>

**Comment by TreeMama** [comment]
@jyang81 - really like this - and the red lettering for the error is helpful.

I kinda prefer the green box though...if breaks up the 'wall of text' effect a bit...would it be a big deal to put it back (the smaller version?).

**Comment by halmueller** [comment]
What would you think about an outline but no fill?

**Comment by TreeMama** [comment]
@halmueller - I think ....nothing at all would be my preference over 'just' an outline. I'll defer to you on this - it does look fine as is. If you prefer this to the fill - lets stick with it.

**Comment by halmueller** [comment]
I have no strong feelings on this beyond making sure it's readable in bright sun.

**Comment by TreeMama** [comment]
@halmueller  that is definitely priority. Let's leave it as is. Thanks for this @jyang81 !

**Comment by TreeMama** [comment]
closing
