### ISSUE TITLE
Provide script for creating App Store screenshots

### ISSUE THREAD

**Issue by halmueller** [TreeMama/iSeaTree-React-Prototype#119]
Create a set of instructions for stepping through the app, and indicate where in that sequence a screenshot should be captured.

This can be the same set of instructions for Android and for iOS. For iOS, at least, the person following the script (and actually creating the screenshots) will have to go through the process 4 times, once for each of 4 specified devices.

After this marketing-oriented task is completed, another volunteer or pair of volunteers can create the screenshots.

**Comment by TreeMama** [comment]
@halmueller - For android the script is in /develop/ https://github.com/TreeMama/iSeaTree-React-Prototype/commit/84385b14eb7cb6c72feed5e632fbf5f011653850

**Comment by halmueller** [comment]
The script/storyboard/instructions look good. It seems platform agnostic to me though (which is good IMO). Any reason to tag it as Android?

Someone who knows Android Play Store requirements should add screen size guidance, to match last paragraph of https://github.com/TreeMama/iSeaTree-React-Prototype/blob/develop/documentation/Release_Instructions.md


>
