### ISSUE TITLE
V2 - Add Android screenshots to Github of the 'new map improvements' - Upload to Google Playstore

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#124]
We should save the graphics here (in the root - like we are doing with the ios graphics). 

This ticket is to create that folder AND add V2 graphics to:

1) the folder AND 
2) google playstore.

We need 2 graphics
1) Need graphics of the new map...showing pictures of the tree icons on the continental USA.
2) Show a graphic - zoomed close of a tree that has both the 'More Tree Info' Link and the "Validate this tree" link is active (example tree that can be used shown in screenshot below).
![image0 (27)](https://user-images.githubusercontent.com/62637055/104238180-0a0f9200-540e-11eb-90fa-f5da723196b0.png)

**Comment by halmueller** [comment]
Related: #119

**Comment by TreeMama** [comment]
done
