### ISSUE TITLE
V2 - fix problem where 'iTree API' values ONLY go to Firebase IF the user selects 'Calculated Tree Benefits'

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#126]
This commit: https://github.com/TreeMama/iSeaTree-React-Prototype/commit/1b949e3a85d56e76978d82ffe0ec91a107f6e005

which is live in testflight as of 1/11/2021 has an error where it ONLY returns the iTree API values IF the user selects 'Calculate Tree Benefits' and THEN hits 'Save'.

This code should still work even if user DOES NOT select 'Calculate Tree Benefits' and Hits 'Save'.

Expected result:

Return iTree API values even if user doesn't select 'Calculate Tree Benefits' in **all** cases that there is a VALID API call.

**Comment by sorratanak** [comment]
Hello, @TreeMama.

I can solve it.

waiting for your reply now.

**Comment by TreeMama** [comment]
@sorratanak there seems to be a bug happening - can you check what's going on - see #139

**Comment by sorratanak** [comment]
1. https://drive.google.com/file/d/159ShJyvwLrjKvoddJoq1nz0Eq37ZTTIC/view?usp=sharing

2. https://reccloud.com/u/znbm1et
