### ISSUE TITLE
V2 - add <CalculatedHeightMeter></CalculatedHeightMeter> to the list of returned values

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#127]
This commit: https://github.com/TreeMama/iSeaTree-React-Prototype/commit/1b949e3a85d56e76978d82ffe0ec91a107f6e005

which is live in testflight as of 1/11/2021 has an error where it is missing the values from:
`<CalculatedHeightMeter></CalculatedHeightMeter>`

Expected result:

Return iTree API values `<CalculatedHeightMeter></CalculatedHeightMeter>` in **all** cases that there is a VALID API call. Otherwise - return <NULL>

**Comment by sorratanak** [comment]
Hello.
I go the issue, correctly.
I can fix it quickly.
Please assign it to me.
Thank you.

**Comment by halmueller** [comment]
Please do this work in a separate feature branch, and then merge that feature branch when the work is done.

Do not commit directly to `develop` or `master`. See the branching guidelines in the README.

**Comment by sorratanak** [comment]
ok, no problem.
