### ISSUE TITLE
V2 (BUG) iTree API seems to be called BEFORE user selects 'SAVE' or 'CALCULATE TREE BENEFITS'

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#139]
it seems like the api is being called whenever all the necessary fields are filled out...which is wrong.

the api should only be called in 2 cases :

1) If the user has filled out all the data and selected 'SAVE' then the api is called to retrieve values to save to firebase (whether the user has viewed the 'CALCULATE TREE BENEFITS' calculator or not - see case #126 ) .

2) IF the user has selected 'CALCULATE TREE BENEFITS' - then the api is called to populate the form

walkthrough of error:

https://user-images.githubusercontent.com/62637055/104551238-6085f780-55eb-11eb-8f65-34a6f35ed014.mov

**Comment by sorratanak** [comment]
1. https://drive.google.com/file/d/159ShJyvwLrjKvoddJoq1nz0Eq37ZTTIC/view?usp=sharing

2. https://reccloud.com/u/znbm1et
