### ISSUE TITLE
V2.1 - Change 'CO2' to 'CO' for the Carbon storage values

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#165]
ToDO:

- for the words circled in red, remove the '2'
- Add 'Volume'
![fixed2](https://user-images.githubusercontent.com/62637055/106337816-0883fd80-6247-11eb-9545-bcf6a9c6077e.png)

**Comment by jyang81** [comment]
closing this.

**Comment by halmueller** [comment]
If we're talking about carbon sequestered, it should be "C", not "CO". CO is carbon monoxide.

**Comment by TreeMama** [comment]
This is an old release. Value shows up as in iTree (in 2.0.3 android / 2.0.4 ios):

<CarbonDioxideStorage Unit="lb">60627.122100841334</CarbonDioxideStorage>
<CarbonDioxideStorageValue Unit="$">1410.0</CarbonDioxideStorageValue>

![image0 (50)](https://user-images.githubusercontent.com/62637055/123885116-956bd980-d901-11eb-89d5-6c1595ed894d.png)
