### ISSUE TITLE
V2.01 - URGENT BUG - Explore page keeps loading...and loading 

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#185]
It appears that something from this checkin: https://github.com/TreeMama/iSeaTree-React-Prototype/commit/c68f7a968975ae4d9e292fb7decfd9ac8904a88d has broken the Explore page.

It is now stuck in a constant cycle of loading.

The checkin was an effort to make sure that the iTree API values (CO2, Carbon, H20 storage) were returned to firebase every time a user *SAVED* a tree (and whether they opened the 'Tree Calculator' or not - prior to saving).

Need to:

1) investigate why this checkin broke the build 
2) fix it
3) roll it back if no fix and investigate another way to retain the iTree values (regardless if the Tree Calculator was opened) on every save
![image0 (40)](https://user-images.githubusercontent.com/62637055/109043347-18e09a00-7686-11eb-8a22-966900e496d9.png)

**Comment by JonathanKoerber** [comment]
I just pushed a fix for this one. I could use a test to see if this is still happening.

**Comment by TreeMama** [comment]
@JonathanKoerber I will test - thanks so much!

**Comment by TreeMama** [comment]
Confirmed fixed in Testflight Build 40 (3/13/21) Thanks @JonathanKoerber !!
