### ISSUE TITLE
V.2.0.1 (BUG) - Make sure the 'Explore' map opens where the user is

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#186]
New user (who hadn't entered any data on the map - and was located in Northern New Jersey) noted that the existing map interface - even when blank - defaults to opening over Seattle.

This is wrong - the default should be that the map opens where the users device is (for the above case, that would be Northern New Jersey).

The user who was testing this feature was using Android - but the same story should apply for iOS.

**Comment by halmueller** [comment]
I predict that a fix for this would solve both platforms.

**Comment by JonathanKoerber** [comment]
Could you have them try this again. I pushed a location fix I would be curious to see if this got taken care of.

**Comment by jaredaritter** [comment]
Similar issue in North Carolina
Data points:

iPhone 4, iOS 14.2
TestFlight: iSeaTree v2.0.1

Also having issues with map starting in Seattle and then transitioning to my area. 

The app is never closed. I log myself out and back in. When going to Explore it flashes Seattle and then find my local area. 
https://user-images.githubusercontent.com/38332939/111051261-cf32d600-841f-11eb-9b79-bb8861366563.mov

The app is closed. I remain logged in. When I go to Explore for the first time it flashes Seattle and then find my local area. 
https://user-images.githubusercontent.com/38332939/111051350-6730bf80-8420-11eb-8a35-25eb33aca7a3.mov

The app is not closed. I remain logged in. I can leave the app, open another app, and when I go to explore it is immediately on my area. 
https://user-images.githubusercontent.com/38332939/111051373-8891ab80-8420-11eb-8fdb-87874671b53d.mov

If you have issues with the .mov file format I can figure out another way to load, the initial .mp4 files were making github angry.

**Comment by TreeMama** [comment]
Note: @jaredaritter is using the Testflight Build #40. Still needs fix. Not closing @JonathanKoerber .

**Comment by TreeMama** [comment]
closing
