### ISSUE TITLE
V.2.0.1 - (Urgent Bug) : Trees sometimes are not being added to map and does not show in logs

### ISSUE THREAD

**Issue by gering92** [TreeMama/iSeaTree-React-Prototype#188]
Video displaying bug: 
https://user-images.githubusercontent.com/80599571/111042617-1191ee00-83f3-11eb-8290-77c050686eb9.mp4

Saving tree takes user to a splash screen while in the process of saving. Appears to be the app restarting, and as a result the save process is not carrying out fully. I got one of the trees I saved to show up, but the others (I believe I attempted to save 6 trees in total) are not showing up on either the logs or on the map that displays my own saved trees. 

Wifi connectivity probably not the issue because the tree that did get successfully saved was uploaded when I was outside and not connected to wifi, and subsequent pictures taken while connected to wifi at my house sometimes worked and sometimes didn't work. 

Username used: geringeorge92
Date: 3/13/21

**Comment by gering92** [comment]
Another test with a dummy pic worked and it now shows up on my personal tree map. The picture was a picture of a blue hydroflask and it was labeled as an American Hornbeam.
Username: geringeorge92
Date: 3/13/2021

**Comment by TreeMama** [comment]
Note: these issues were found in the testflight build : 40

**Comment by jaredaritter** [comment]
Similar issue on TestFlight Build #40
iPhone 7, iOS 14.2

Occurred three times in today's testing. After looking at logs, it appears that data may sometimes make it to DB. Out of 21 submissions I have 18 entries. Some may have been flagged as 'not tree', but the two submissions of broccoli are not found in DB.

Anecdotally occurred most often on initial photo submission after not using app for a while. Subsequent photos worked as intended.

**Comment by JonathanKoerber** [comment]
It may be worth while to retest this to see if it is still happening.  There has been a lot of updates since the bug first logged.
