### ISSUE TITLE
V.2.0.3 - (Urgent Bug) : 'Unknown' trees saving iTree values 

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#193]
Tested in:

testflight Build 41 (2.0.1)

Problem:

Trees entered as 'Unknown' are being shown as having iTreeAPI values (CO2Sequestered, DryWeight, etc). There are NO values that should show up in the case of an 'Unknown' tree (note: you need to know the species in order to generate an appropriate call to the iTreeAPI). 

This leads me to believe this is some sort of caching problem. I think the legacy values from a tree (of a specific species) are being retained somehow. Observe below - how to different cases of an 'Unknown' tree have the same DryWeight value.

![Capture](https://user-images.githubusercontent.com/62637055/112897243-38f3e680-9094-11eb-815f-235b70e27cf1.JPG)
![Capture2](https://user-images.githubusercontent.com/62637055/112897246-3abdaa00-9094-11eb-837a-9616d02c41fd.JPG)

ToDO:

 - check that the iTreeAPI is NOT ever called when a tree is entered as 'Unknown'. ALL 'iTreeAPI' fields should return 'NULL' when the species is 'Unknown'
- check that the iTreeAPI call changes when the species changes (test by entering 2 different trees - the result should be different values for the 2 different trees).

**Comment by JonathanKoerber** [comment]
So this is caused by the benefit values are stored in async storage and are only cleared when a new set of values are added. This is also causing incorrect values to be stored for trees with valid names that haven't had TreeBenifit called on them as the same zombie values are added to a new entry.  In addition, the version of async storage that was being added to the app has been deprecated. I am working on a fix.

**Comment by TreeMama** [comment]
Verified the fix on build42 (2.0.1) - thank you so much @JonathanKoerber !

Test:
1) entered a valid species and made sure it calculated the iTree values correctly. Then saved entry.
2) Entered a 2nd entry - but with species 'Unknown'. Made sure the data was NULL for all the iTree values.

![verified](https://user-images.githubusercontent.com/62637055/116646671-8383af80-a92d-11eb-9e5b-f59d2788921e.JPG)

**Comment by TreeMama** [comment]
Just saw this happen again on v 2.0.2 (build 44). Android (os 11). reopen for fix on 2.0.3

entry: iW8C44HL0kFtsflkYFYT

https://console.firebase.google.com/u/1/project/iseatree-dev/firestore/data/~2Ftrees~2FiW8C44HL0kFtsflkYFYT

**Comment by TreeMama** [comment]
It looks like it is fixed (again) in Build 45....though seeing other problems (as noted in #195 ) - closing for the moment.
