### ISSUE TITLE
V.2.0.3 : Changing the species name on a tree - NO automatic name update (should update right when changed)

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#195]
Tested in:

testflight Build 41 (2.0.1)

Expected behavior:

- RIGHT after changing a species name of an 'Unknown' tree, the new name should show up here (right now it doesn't).
![image1 (8)](https://user-images.githubusercontent.com/62637055/112899843-832a9700-9097-11eb-9608-e3fb25714368.png)
![image0 (44)](https://user-images.githubusercontent.com/62637055/112899849-84f45a80-9097-11eb-869a-1e046f885f14.png)

**Comment by ryanflynndev** [comment]
I'll check this one out

**Comment by TreeMama** [comment]
Fixed in Build 45 - closing
