### ISSUE TITLE
2.0.3 - If user changes species name - run the iTreeAPI

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#196]
Once #195 is resolved - a new feature request.

ToDO:

Provide a check after a user changes a species name from 'Unknown' to a known species run the iTreeAPI and generate new values to replace the NULL values in the database.

- make sure that if there is not a valid iTreeAPI call that the values remain NULL
- if there is a valid iTreeAPI call , UPDATE the values for
1) CO2Sequestered
2) CO2SequesteredValue
3) CORemoved
4) CORemovedValue
5) CalculatedCrownHeightMeter
6) CalculatedCrownWidthMeter
7) CalculatedHeightMeter
8) CarbonDioxideStorage
9) CarbonDioxideStorageValue
10) CarbonStorage
11) DryWeight
12) Evaporation
13) Interception
14) NO2Removed
15) NO2RemovedValue
16) O3Removed
17) O3RemovedValue
18) PM25Removed
19) PM25RemovedValue
20) PotentialEvaporation
21) PotentialEvapotranspiration
22) RunoffAvoided
23) RunoffAvoidedValue
24) SO2Removed
25) SO2RemovedValue
26) Transpiration

- note: you will need to include the location information of what was ORIGINALLY recorded when the tree was first entered - that data is saved in the backend in 
1) CityName
2) NationFullName
3) StateAbbr

- You will also need to include the information that was ORIGINALLY recorded when the tree was first entered - that is
1) DBH (map this value for 'DBHInch=')
2) treeConditionCategory (map for the 'condition=' part of the iTreeAPI see issue #70 )
3) crownLightExposureCategory (map this value for 'CLE=')

![image1 (8)](https://user-images.githubusercontent.com/62637055/112901110-31830c00-9099-11eb-8d4b-237120b20b5c.png)

**Comment by halmueller** [comment]
We probably need this logic whenever the species is changed, even from Known1 to Known2. So a didChangeSpecies() callback of some sort?

**Comment by TreeMama** [comment]
Build 45 @monikap0612  has this bug (found in testflight):


- showing/saving trees in WRONG location on the Explore page
- recording the wrong coords
- entering invalid (note the negative numbers data (possibly caused by a bad api call to the iTreeAPI - in this case the trees were showing up in India - even though the react-native location package was correct in identifying the tree as in Shoreline, WA USA).

To repo: 
1) enter tree as 'Unknown" species with "220.38" DBH
2) after "Unknown" is saved- go to "Explore" page...noticed that tree location & coords is showing up in India.
3) change species to "Trident Maple" in the app.
4) Note: negative erroneous values saved from iTreeAPI...
(is this because the coords are
India? Notably  CityName/CountyName/StateAbbr are correct though...!)

![right_location_but_negative_values](https://user-images.githubusercontent.com/62637055/122684944-6d6fce00-d1bd-11eb-882c-72de9ce65a8a.png)
![wrong_coords](https://user-images.githubusercontent.com/62637055/122684947-719beb80-d1bd-11eb-9e62-2ee39877117a.png)
![correct_coords](https://user-images.githubusercontent.com/62637055/122684950-73fe4580-d1bd-11eb-8632-a0f133e04a9e.JPG)
![image0 (46)](https://user-images.githubusercontent.com/62637055/122684960-811b3480-d1bd-11eb-971a-5f19d30e90ca.jpeg)

**Comment by TreeMama** [comment]
location issue looks fixed as of build 46.

tested api callback - results looked good.
