### ISSUE TITLE
V2.0.3 (Maps Feature): Add a warning screen if there are no tree's entered

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#200]
Problem:

New users get to the 'Individual map' on the 'Explore' page - and don't understand why there are no trees.

Solution:

Add a warning anytime the user's 'treeCount' is 0 - then show this error (JUST FOR THE individual map).

“Welcome! When you enter your first tree, it will show up on the map.”

![Capture](https://user-images.githubusercontent.com/62637055/122482362-429b3500-cf85-11eb-8a8a-69c0393cf87d.JPG)

**Comment by halmueller** [comment]
Slightly friendlier wording, to stay away from “you did it wrong” sense:

“Welcome! When you enter your first tree, it will show up on the map.”

>

**Comment by czhou578** [comment]
I suggest having a card that displays the message, and that it blurs out the background, signaling for further action. Kind of like the following....

![image](https://user-images.githubusercontent.com/42430035/118376944-d5f4db00-b57f-11eb-999b-5ff2cf4672e6.png)

**Comment by TreeMama** [comment]
Tested in build 45. Looks like its working - thanks @monikap0612 

![image0 (48)](https://user-images.githubusercontent.com/62637055/122685267-34d0f400-d1bf-11eb-8240-2dbb371f185b.jpeg)
