### ISSUE TITLE
Bug (2.0.1): Adding Tree feature not working on phone with Android 11

### ISSUE THREAD

**Issue by czhou578** [TreeMama/iSeaTree-React-Prototype#201]
I am using the iSeaTree app that I downloaded from the Google Play Store. I am using an Android phone that is running Android 11, which is the newest update. 

I am trying to add a tree, but there are certain fields in the section that would not allow me to select data. More specifically, the popup that is supposed to display the possible options for me to select, is not showing at all.

Here is a picture:

![Screenshot_20210515-134326](https://user-images.githubusercontent.com/42430035/118377721-d5f6da00-b583-11eb-8165-b45a2200d388.jpg)

Also, not sure if this link will prove to be helpful in solving this issue.

https://blog.expo.io/expo-sdk-41-12cc5232f2ef

Colin Zhou

**Comment by TreeMama** [comment]
Note: I tried to repo this for OS 10 & 9 - and wasn't able too - BUT I was did find #204 (another bug). Need someone with an 11 OS to confirm...

**Comment by TreeMama** [comment]
tested that it works on an android os: 11.
