### ISSUE TITLE
Bug (2.0.1 release): Tree Benefits Calculator not working on ANY Android devices

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#204]
Testing devices:
2 samsung models:  'SM-G950U1' (Android 9 OS) and 'SM-T290' (Android 10 OS). On May 17 & 19 2021.

The tree benefits calculator couldn't be called on either device - even after filling out all the required information. Data still could be Saved though (which indicates this wasn't a wifi/cell connection problem). See video below for demo.

Expected fix:
Tree Benefits calculator should be active and call the iTree API everytime all the req. data fields are filled out.

https://user-images.githubusercontent.com/62637055/119912852-1bff5680-bf11-11eb-9fa5-e20da52bbc34.MOV

**Comment by halmueller** [comment]
I haven’t tested. But it feels farfetched to me that this bug would be absent on iOS, given that it’s present on Android. Don’t they use the same code path?

Hal

**Comment by TreeMama** [comment]
@halmueller yeah, I checked ios - and it wasn't a problem there. @monikap0612  is going to check this out

**Comment by TreeMama** [comment]
t5ested and found working on an os 11
