### ISSUE TITLE
V2.1.1: (ENHANCEMENT - IOS LAUNCH REQ) Add ability to delete user account within app; deadline Jan 31, 2022

### ISSUE THREAD

**Issue by halmueller** [TreeMama/iSeaTree-React-Prototype#208]
Per the changes to the Apple iOS App Store announced June 2021, any app that allows creation of a user account within the app must also allow deletion of the account within the app.

This is not a bug right now, but at some indeterminate time in the future it will cause iOS app rejection if it's not addressed.

**Comment by JonathanKoerber** [comment]
How would we treat the orphaned data? Do we need to only delete the user's credentials or the trees as well?

**Comment by halmueller** [comment]
Excellent question. I don’t think we have to follow GDPR-like standards, but let me take this one for research…with peers and in apple resources. 

Hal Mueller 
***@***.***

**Comment by halmueller** [comment]
I brought this up at the (in-person! yay!) Seattle Xcoders gathering last night. The requirement is stated in the App Store review guidelines, but there's no supporting information anywhere else.

Several people pointed out the similarity to Gitlab and other similar open source contribution sites. You agree to a contributor's license, which means that anything you contribute stays with the project. If you leave (by deleting your account), the contributions (i.e. your git commits) are not deleted. They are instead marked with contributor ID of -1.

A dev at Rover.com mentioned that he thinks Rover is one of the organizations Apple has in mind for this requirement. Rover in fact does have a way to delete the account inside the app, but it's buried and hard to find.

We could/should do the same thing. When you create your tree observer account, you agree that your contributions fall under whatever data license/contributor agreement we have in place. When/if you leave, mark all that user's contributions as coming from "deleted" or "unknown" or something. The contributions stay in place, but they can't be traced to an individual former observer.

**Comment by halmueller** [comment]
Per https://developer.apple.com/news/?id=mdkbobfo, this requirement will be enforced for all app updates submitted on or after January 31, 2022.

**Comment by andaniel2029** [comment]
> Per https://developer.apple.com/news/?id=mdkbobfo, this requirement will be enforced for all app updates submitted on or after January 31, 2022.


Hello, @halmueller  and @TreeMama.

Let me check again before starting this task.

When a user wants to delete an account from the app, should I do like this?

**- set 'isDeleted' = 'Y' for user document**
**- set 'isDeleted' ='Y' for trees created by that user**

It is the right direction now?

thanks.

**Comment by halmueller** [comment]
This is just my opinion; @TreeMama has the final call. 

I don't know exactly what the user document is. But I would expect that it would be deleted, irretrievably. Trees would stay in the system, with the contributor ID set to -1, or maybe left alone with an untraceable GUID if we might want to see all contributions grouped by fully anonymized former members. There's no requirement to delete their observation data, just their personal information. 

If I delete my Open Street Map or GitHub account, my contributions to the map or to projects remain intact. That's what I think we should mimic. 

If I join, measure some trees, delete my account, then rejoin, it should be completely impossible to associate measurements from my first account with the new account. 

Reposting my comment from June:


> Several people pointed out the similarity to Gitlab and other similar open source contribution sites. You agree to a contributor's license, which means that anything you contribute stays with the project. If you leave (by deleting your account), the contributions (i.e. your git commits) are not deleted. They are instead marked with contributor ID of -1.

**Comment by andaniel2029** [comment]
> This is just my opinion; @TreeMama has the final call.
> 
> I don't know exactly what the user document is. But I would expect that it would be deleted, irretrievably. Trees would stay in the system, with the contributor ID set to -1, or maybe left alone with an untraceable GUID if we might want to see all contributions grouped by fully anonymized former members. There's no requirement to delete their observation data, just their personal information.
> 
> If I delete my Open Street Map or GitHub account, my contributions to the map or to projects remain intact. That's what I think we should mimic.
> 
> If I join, measure some trees, delete my account, then rejoin, it should be completely impossible to associate measurements from my first account with the new account.
> 
> Reposting my comment from June:
> 
> > Several people pointed out the similarity to Gitlab and other similar open source contribution sites. You agree to a contributor's license, which means that anything you contribute stays with the project. If you leave (by deleting your account), the contributions (i.e. your git commits) are not deleted. They are instead marked with contributor ID of -1.

User document means users's collection document that contains user account information.

![image](https://user-images.githubusercontent.com/51064752/143175551-8bb7e6ca-ab5c-4ca9-8522-54ce11042dff.png)

**Comment by halmueller** [comment]
Gotcha. I think we should delete the user document, keep the trees, and nil out the link from each tree to the former user document (or whatever sensible way there is to maintain DB integrity).  

Hal

**Comment by andaniel2029** [comment]
> Gotcha. I think we should delete the user document, keep the trees, and nil out the link from each tree to the former user document (or whatever sensible way there is to maintain DB integrity). Hal
> […](#)
> On Nov 23, 2021, at 8:34 PM, bestw ***@***.***> wrote: ﻿ This is just my opinion; @TreeMama has the final call. I don't know exactly what the user document is. But I would expect that it would be deleted, irretrievably. Trees would stay in the system, with the contributor ID set to -1, or maybe left alone with an untraceable GUID if we might want to see all contributions grouped by fully anonymized former members. There's no requirement to delete their observation data, just their personal information. If I delete my Open Street Map or GitHub account, my contributions to the map or to projects remain intact. That's what I think we should mimic. If I join, measure some trees, delete my account, then rejoin, it should be completely impossible to associate measurements from my first account with the new account. Reposting my comment from June: Several people pointed out the similarity to Gitlab and other similar open source contribution sites. You agree to a contributor's license, which means that anything you contribute stays with the project. If you leave (by deleting your account), the contributions (i.e. your git commits) are not deleted. They are instead marked with contributor ID of -1. User document means users's collection document that contains user account information. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

thanks a lot, @halmueller .

**Comment by TreeMama** [comment]
@andaniel2029 - I think Hal is right on this one. Though I have noticed, as is alluded here - because of the links between the user table and the trees table - any deletion of users comes with the warning that associated content in trees will be deleted. Because we DO need to keep the tree data - We will probably have to do the step of removing the link between the user and their data before deleting the user....

**Comment by andaniel2029** [comment]
Finally, I should do like this:

**- delete the document in the users collection**
**- set 'userId' ='-1' or 'null' for trees documents created by that user**

**Comment by andaniel2029** [comment]
hello, @TreeMama 

I lost the envVariables.ts file.

can you send it again, please?

thanks.

**Comment by andaniel2029** [comment]
hello, @TreeMama 

One more thing.

I gonna add a delete icon at that position.

So when the user clicks that icon, I will display confirm modal(yes/no).

![image](https://user-images.githubusercontent.com/51064752/143420806-1239da6b-8cde-47aa-bd54-96829ce67231.png)

It is ok, if you have a better idea, please let me know.

thanks.

**Comment by andaniel2029** [comment]
hello, @TreeMama 

I finished this task.

![image](https://user-images.githubusercontent.com/51064752/143496275-30e64aa8-d11c-4f96-8f9e-b68369a51916.png)

**If the user clicks the 'ok' button, then Trees documents will be updated 'userId' = -1, and the user document and account will be deleted as well.**

Let me push the codes also.

https://github.com/TreeMama/iSeaTree-React-Prototype/tree/enhance/delete_account_func

https://github.com/TreeMama/iSeaTree-React-Prototype

please check, thanks.

**Comment by TreeMama** [comment]
Hi @andaniel2029 - looks like an awesome addition. Can we change a few things?

1) The msg needs to change on the delete account option. Can you change it to:

Confirmation

Do you want to delete your account? If you select "OK"  all user data will be impossible to 
restore in the future.

                                                     OK                                      CANCEL

2) Since we have a msg warning for the delete account option - we should probably have a msg warning for our logout option (it is the item in blue). Can you add this? When the user selects ok they proceed to the login screen. This is the msg for it:

Confirmation

This will log you out and take you to the login screen. Ok?

                                                    OK                            CANCEL


        
![143496275-30e64aa8-d11c-4f96-8f9e-b68369a51916](https://user-images.githubusercontent.com/62637055/143500821-67846160-c625-422f-88f1-ef165f43b080.png)

**Comment by andaniel2029** [comment]
ok

**Comment by andaniel2029** [comment]
> Hi @andaniel2029 - looks like an awesome addition. Can we change a few things?
> 
> 1. The msg needs to change on the delete account option. Can you change it to:
> 
> Confirmation
> 
> Do you want to delete your account? If you select "OK" all user data will be impossible to restore in the future.
> 
> ```
>                                                  OK                                      CANCEL
> ```
> 
> 2. Since we have a msg warning for the delete account option - we should probably have a msg warning for our logout option (it is the item in blue). Can you add this? When the user selects ok they proceed to the login screen. This is the msg for it:
> 
> Confirmation
> 
> This will log you out and take you to the login screen. Ok?
> 
> ```
>                                                 OK                            CANCEL
> ```
> 
> ![143496275-30e64aa8-d11c-4f96-8f9e-b68369a51916](https://user-images.githubusercontent.com/62637055/143500821-67846160-c625-422f-88f1-ef165f43b080.png)

I pushed it just.

**Comment by halmueller** [comment]
What branch is this in?

Hal

**Comment by andaniel2029** [comment]
> What branch is this in? Hal
> […](#)
> On Nov 25, 2021, at 1:21 PM, TreeMamaSEA ***@***.***> wrote: ﻿ Hi @andaniel2029 - looks like an awesome addition. Can we change a few things? The msg needs to change on the delete account option. Can you change it to: Confirmation Do you want to delete your account? If you select "OK" all user data will be impossible to restore in the future. OK CANCEL Since we have a msg warning for the delete account option - we should probably have a msg warning for our logout option (it is the item in blue). Can you add this? When the user selects ok they proceed to the login screen. This is the msg for it: Confirmation This will log you out and take you to the login screen. Ok? OK CANCEL — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

https://github.com/TreeMama/iSeaTree-React-Prototype/tree/enhance/delete_account_func

enhance/delete_account_func branch.


-bestw

**Comment by TreeMama** [comment]
Tested on testflight build 54. Verified on an ios (14.7.1) that I could create a new user (testusrr), enter tree data, then delete the user using the 'delete' icon on the profile screen. Though the user data was wiped from the 'user' table, the tree data was retained with a new userID = '-1'.
