### ISSUE TITLE
Enhancement (v2.0.3): Modify DBH user entry to offer options to calculate DBH from circumference

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#209]
ToDo: 

Create and add the functionality outlined below.
[Scan-06-14-21.pdf](https://github.com/TreeMama/iSeaTree-React-Prototype/files/6651451/Scan-06-14-21.pdf)

**Comment by TreeMama** [comment]
@monikap0612 - looks good. However, the default numbers aren't accurate. Would it be possible to fix them to be real calculated example values?
![IMG_2304](https://user-images.githubusercontent.com/62637055/122705739-30322d00-d20b-11eb-88c5-b31485509fd0.png)

**Comment by halmueller** [comment]
Friendly reminder that this work should be happening in a feature branch. I’m happy to do a live walkthrough if anyone needs help. 

Hal Mueller 
***@***.***

**Comment by TreeMama** [comment]
Looks fixed as of build 46 - thanks @monikap0612
