### ISSUE TITLE
V2.1.1 -V3: (NEW FEATURE) AR Ruler Measurement (beta) for DBH 

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#219]
ToDO:

** note: to add the AR option **it seems VERY likely** that we might have to [convert the expo project to straight react-native](https://forums.expo.dev/t/convert-expo-project-into-vanilla-react-native/33501)**

- Try to add a beta AR option for measuring the DBH of a tree - call it "(beta) Measure with camera"
- The AR will allow the user to measure BOTH multi-stem trees (where the DBH of everything at 4.5 feet of height are measured - then summed) AND single stem entries
- The final value will be added to the 'Add new' screen (in the 'Measure with Camera' text box) with the 'Estimate' box checked
- There also will be an additional binary field added to the backend firebase database called 'AR_Measured'  - which will be marked as 'true' everytime a user uses this method to measure the DBH
-  ALSO (very important) Make sure the DBH value is populated with the numeric value from the AR_Measurement! (Note: DBH is a required input - and must be present in order for a user to use the 'Tree Benefits Calculator' or save a tree)
- 'estmated_dbh' will be marked also as 'true' everytime this method is used
- Based on the package changes needed to convert to react-native, necessary updates to the [README file](https://github.com/TreeMama/iSeaTree-React-Prototype#readme) are included as part of this ticket. 

Once the above is done/tested:
- add 3 new graphics into the tutorial  (after the current 'Add new' tutorial page) -->
- 1st tutorial graphic that shows the DBH options box (AR included - marked as 'beta') and the text should read: "To calculate DBH (Diameter at Breast Height) you can either measure the tree yourself..." (show a picture with an arrow pointing to the "Measure & Enter DBH manually" text box)
- 2nd tutorial graphic says "...or use our AR-driven camera detection option." (show a picture with an arrow pointing to the "Measure with camera" text box).
- 3rd tutorial graphic shows the DBH AR screen (looking at a tree) and says "To use the camera option, simply line up the tree trunk with the red lines on the screen."  

This feature will be released in a future release with the note "beta" (on the DBH selection options).

Current examples to follow for the AR measure design screen (similar to our design, the user aligns the tree width to the 2 vertical lines):
https://www.arboreal.se/en/new-method-to-measure-a-tree/

Check this thread for possible react-native package options (viro is suggested)

https://www.reddit.com/r/reactnative/comments/dwkwvj/is_react_native_have_similar_package_like_ar_ruler/

viro:
https://github.com/viromedia/viro
![E-z-8PVVEAIIRCH_edits](https://user-images.githubusercontent.com/62637055/144547056-b4d8de5f-d484-4a91-ab2f-6465f08544a5.jpg)

**Comment by kailynnelson** [comment]
Working on this design! 2-3w timeline.

**Comment by kailynnelson** [comment]
Progress: https://whimsical.com/iseatree-3pp22n5L8rax4UsN4wvLsp 

Going out of town starting Wednesday and won't be back until next week, so I'll check in again two weekends from now.

**Comment by TreeMama** [comment]
Hi @kailynnelson this is such an exciting start! I posted my comments in whimsical (not sure if you can see them) - but if not - I've also added them here. As soon as you can help us finalize this - we can help monika get started!

Thank you so much!
![Capture1](https://user-images.githubusercontent.com/62637055/130714166-1b2ba66a-05a3-432a-b3a2-448723ea8497.JPG)
![Capture](https://user-images.githubusercontent.com/62637055/130714170-6d6520be-74ad-493d-8bc9-3be09b1cc308.JPG)

**Comment by kailynnelson** [comment]
Just emailed you back, Ari - I saw your comments and just gave you editor permission to be able to make more edits yourself. I've had some recent scheduling changes, so I'm not sure when I'd be able to come back around to this!

**Comment by TreeMama** [comment]
Thanks @kailynnelson !

Enclosed is the final design - ready for development!
![E-z-8PVVEAIIRCH_edits](https://user-images.githubusercontent.com/62637055/144547076-2fce6d6f-81bf-420d-b33a-79061e41faad.jpg)

**Comment by mhaidli** [comment]
I looked into adding AR ruler functionality to the app. unfortunately I could not get the code to work given time limitations, but it was still a useful exercise and there are some insights I can share.

Overall I think that adding it through Viro is probably the way to go. The tutorial I used is found here: https://docs.viromedia.com/docs/viro-platform-overview. I couldn't get it to work, but the tutorial is well-written and with more time to play around with it it could work.

The only downside to Viro is that there seems to be no code example of an AR ruler. This means that we would have to use Viro's API to somehow create our own way to measure distance, which may be complicated (see https://github.com/viromedia/viro/issues/807 and https://github.com/viromedia/viro/issues/54)

An alternative could be using ARCore (https://shibuiyusuke.medium.com/measuring-distance-with-arcore-6eb15bf38a8f) for android or ARKit for iOS (see https://www.thedroidsonroids.com/blog/how-to-create-a-measuring-app-with-arkit-in-ios-11 or https://virtualrealitypop.com/ios-11-tutorial-how-to-measure-objects-with-arkit-743d2ec78afc).

**Comment by andaniel2029** [comment]
I tried a lot of research to implement this feature.

during development, the library or dependencies for measuring dbh of the tree may be changed, the main goal is to get the dbh value.

- the important point is to get the distance from the camera to the tree and the rate of the distance unit
- once the user get the image of the tree, then need to generate depth maps from it
- extract tree position and width of the tree
- compare the distance from the camera to the tree with the width of the tree based on the rate of the unit
- need to control the rate value regarding the experimental values

it requires some maths and AI technologies as well


here is the GitHub repository link for depth map.

https://github.com/nianticlabs/monodepth2

**Comment by christyheaton** [comment]
Testing notes (Feb 24 2022 Android APK)

1) Negative values are always invalid - they should never show up as a result. Instead when the math calculates a negative value (like the '-298 in' here) can you have a pop up - which can be closed - that appears and says 'Calibration error! Please try again.' Also - there use to be a setting on the DBH entry box that the value could never be negative - can we turn that back on?

2) Can we make the accelerometer 'x, y, z' text values bold and more visible? Also can they be moved farther away (to the left) from the camera icon (or make the camera icon slightly smaller so there is less chance of overlap?)

![Capture1](https://user-images.githubusercontent.com/2043319/156255231-af39c1af-4554-44aa-b3d4-0013644447cc.JPG)

**Comment by TreeMama** [comment]
@christyheaton (thanks for testing - and thank you @andaniel2029 for this great new tool!)

I'd add to Christy's #1 test note (the negative values note) that maybe the measuring process starts over again after the user closes the 'Calibration error! Please try again.' msg box.

**Comment by christyheaton** [comment]
Testing notes:

Works well with medium trees where the trunk is clearly visible!

Some changes that would be helpful:

Instead of having to click the "?" icon to see instructions of how to use the app, have the following text appear by default when you open the DBH calculator:

"Fit the width of the tree trunk at breast height (4.5 ft) between the two lines, then hit the "check icon". (For multiple trunks, select the "?" at bottom of screen)."

The, when user hits the "?" the message should show up with the instructions for multiple trunks (as a popup, perhaps?):

"Multiple Trunks: For each individual trunk, fit the width of the trunk at breast height (4.5 ft) between the two lines. Select "Enter Another" to add the next trunk."

After the user has taken the first measurement and clicked the check icon, have the text in the screen say:

"Center the line at the bottom of the tree, then touch the "camera icon"."

**Comment by TreeMama** [comment]
Now available for all users in release 63!! Great job team (@christyheaton and @andaniel2029 and @kailynnelson )!
