### ISSUE TITLE
iOS build instructions: README.md does not reflect reality

### ISSUE THREAD

**Issue by halmueller** [TreeMama/iSeaTree-React-Prototype#235]
Modify README.md with brief Cocoapods non-usage instructions, and notes about code signing and developing on local non-credentialed device.

Requires issue #234 to be done first.

**Comment by halmueller** [comment]
In progress, branch `feature/ios-documentation`. Some edits in that branch will affect issue #241.

**Comment by TreeMama** [comment]
Closing
