### ISSUE TITLE
Update the Android section of the README 

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#241]
10/14 hackathon efforts showed some incompletion in the documentation steps of the README file. Please fix so new users know how to get started in Android Studio with the build.

Please open an feature branch (called /read-me-android-updates/) and edit the readme there.

Lack of available info on:

- Oracle/Java installers needed
- ...anything else?

Focus ALOT on this section:

**Interacting with the Android Simulator**

Add a section for the binaries:
node
watchman

Also - add a section for general troubleshooting and about How/Why to use this command:

export ANDROID_HOME=/Users/<username>/Library/Android/sdk/

ANDROID_SDK_ROOT=E:\Android\sdk\

**Comment by halmueller** [comment]
In feature/ios-documentation I have pulled Android and iOS notes into separate files in the `documentation` directory. I'll merge my WIP so you can see this.

If you have already created your branch, you will need to pull `develop` and then merge `develop` into your working branch. Steps (basic git, you probably know this already):

Commit your current changes in your working branch. Then
```
git checkout develop
git pull
git checkout feature/<your working branch>
git merge develop
```

**Comment by halmueller** [comment]
#235 and #243 are done and merged.

**Comment by TreeMama** [comment]
@andaniel2029 

This is the area to focus on updating
![Capture](https://user-images.githubusercontent.com/62637055/137429363-86d61b3c-ed89-4e7c-9ccd-72c4c6538472.JPG)

**Comment by andaniel2029** [comment]
got it, thanks for your all.

**Comment by mhaidli** [comment]
(A few notes and things to keep in mind on my my experience trying to get everything to work, running an android version on a Windows Machine)

* There is a need to check the environment variables (Start Menu -> Change your environment variables -> Environment Variables -> Once there, add ANDROID_HOME that points to < path-to >\Android\Sdk to Users and System variables, as well as JAVA_HOME that points to < path-to >\Java\jdk1.8.0_201 to User variables)
* To use an emulator, you need to install Intel(R) Hardware Accelerated Execution Manager (HAXM), which may or may not install on your machine (it didn't on mine)
* If instead you want to use your phone as an emulator, you will need to enable USB debugging in your phone, and then plug it in. Despite doing this, sometimes windows won't recognize your plugged in android device. in that case, you need to go to command line and run `adb devices` to see a list of connected devices. You should see something like `1443da2267859bz device.`
* You then may have to add this device id as a flag when executing the command (i.e.,  `npx react-native run-android --deviceId=1443da2267859bz`
* You will need to have 2 command prompts open. One to run `yarn start`, another to run `npx react-native run-android --deviceId=1443da2267859bz` (both from the root of the project)

**Comment by TreeMama** [comment]
As of 10/22 this looks good - thanks @mhaidli (for the astute guidance) and @andaniel2029 !
