### ISSUE TITLE
V 2.11: Jest Testing - test the validity of the species.json

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#251]
Especially once we release feature #197 we will need to be particularly careful with our species.json data.

I recommend the Jest test team look into creating a series of validation test for the species.json

The following are suggested tests for this 1 specific file:

Test 1:
Check that all necessary fields are populated for every tree species. If test fails return WHICH fields failed and the "Common" name and ID # of the failed tree.

Necessary populated fields are:
"COMMON"
"TYPE"
"SCIENTIFIC"
"ID"
"ITREECODE"
"FULL_PIC"
"GENUS"
"DESCRIPTION"

Test 2:
(This will have to wait till #197 is complete, but you can set up the test to fail now)
Check that all photos called in "FULL_PIC" and "THUMB_PIC" return a valid url response.

**Comment by andaniel2029** [comment]
It is done.

Android build success and works on the device also.

https://github.com/TreeMama/iSeaTree-React-Prototype/pull/268
