### ISSUE TITLE
V 2.1+ (react native upgrade to 0.64.1)

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#252]
ToDO:

Upgrade react-native (in it's own feature branch - called 'react-native-upgrade-0.64')

Once tested - push to /develop
![Capture1](https://user-images.githubusercontent.com/62637055/141661622-163de48c-f66c-4b79-9489-9aad0be7158c.JPG)
/

**Comment by andaniel2029** [comment]
https://github.com/TreeMama/iSeaTree-React-Prototype/issues/256

My suggestion is to create a new project using react-native CLI and integrate current modules there.
