### ISSUE TITLE
V2.1+: upgrade node-notifier

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#253]
ToDO:

Upgrade node-notifier (in it's own feature branch - called 'node-notifier-8.01')

Once tested - push to /develop
![Capture2](https://user-images.githubusercontent.com/62637055/141661648-fbc5d850-beaa-4b14-bbda-3322138e9113.JPG)
/

**Comment by andaniel2029** [comment]
https://github.com/TreeMama/iSeaTree-React-Prototype/issues/256
