### ISSUE TITLE
V2.1+:  upgrade node-fetch 

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#254]
TODO

Upgrade node-fetch (in it's own feature branch - called 'node-fetch-2.6.1')

Once tested - push to /develop
![Capture3](https://user-images.githubusercontent.com/62637055/141661688-d5325a25-7045-4a55-a26f-6ec83ea7178e.JPG)
/

**Comment by andaniel2029** [comment]
https://github.com/TreeMama/iSeaTree-React-Prototype/issues/256
