### ISSUE TITLE
V2.1+: upgrade xmldom

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#255]
TODO:

Upgrade xmldom (in it's own feature branch - called 'xmldom-upgrade') to either version that works ( ^0.5.1 || ^0.6.1 || >=0.7.0)

Once tested that nothing broke- push to /develo
![Capture4](https://user-images.githubusercontent.com/62637055/141661723-1341926e-603f-4988-a7f1-d4a0010c4c19.JPG)
p/

**Comment by andaniel2029** [comment]
https://github.com/TreeMama/iSeaTree-React-Prototype/issues/256
