### ISSUE TITLE
V2.1+: Find out why Build 55 doesn't work on Android 11

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#257]
ToDO:

Fix the reason the "Calculate Tree Benefits' button isn't working on Android 11.

https://user-images.githubusercontent.com/62637055/141661778-9eba2aa2-6698-467b-a9cc-75568f43e99a.mp4

..

**Comment by andaniel2029** [comment]
Original codes.

```
<Button
        mode="outlined"
        onPress={loadBenefits}
        disabled={!canCalculateBenefits}
        icon="calculator"
      >
```

Later.

```
<Button
        mode="outlined"
        onPress={() => loadBenefits()}
        disabled={!canCalculateBenefits}
        icon="calculator"
      >
```

**Comment by andaniel2029** [comment]
I built the release version apk and set it for the test. 

waiting for feedback for it now.

**Comment by christyheaton** [comment]
Test passed

**Comment by andaniel2029** [comment]
> Test passed

cool :)
