### ISSUE TITLE
firebase development database is not working firebase credentials 

### ISSUE THREAD

**Issue by andaniel2029** [TreeMama/iSeaTree-React-Prototype#281]
we have prod/dev database for the app now.

When we use dev firebase credentials (googleSerivce.json/GoogleService-Info.plist), authentication (login/register) is not working now.

**Comment by halmueller** [comment]
Was it ever working? When did it stop working?

**Comment by andaniel2029** [comment]
> Was it ever working? When did it stop working?

I am not sure.

Btw, @TreeMama and I got an issue when we help to run the iOS project for another person.

So made this ticket.

**Comment by halmueller** [comment]
Build error or runtime error? What's the error message? Building what Xcode Target? Device or Simulator?

**Comment by andaniel2029** [comment]
No, everything is ok.

Build iOS project successfully.

But when he wants to register a new account or login in there, it doesn't work (in that case, we used development mode credentials ).

So When we change it to the prod version, it works.

**Comment by andaniel2029** [comment]
hello, @TreeMama .

I solved this problem.

The problem was the google cloud project and API restriction setting.

Now, it works for android and ios now.

please check, thanks.
