### ISSUE TITLE
V 3.+ : (ML ENHANCEMENT) ML detection of trees to promote them to "isValidated = NEEDS VALIDATION"

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#296]
ToDO:

- Try to automate the promotion of 'isValidated=SPAM' /trees/ data to 'isValidated=NEEDS VALIDATION' if the url image is definitely a tree (or leafy plant of some sort)
- Maybe try to utilize the[ ML Kit from Firebase](https://www.zealousweb.com/everything-you-need-to-know-about-ml-kit-for-firebase/)
- Species identification is currently NOT of interest, the only real concern is identify all images that are indeed a tree (or plant) of some sort (and if they ARE a tree set 'isValidated=NEEDS VALIDATION'. IF THEY aren't a tree - then DO NOTHING and the field will remain 'isValidated=SPAM' ).
- This automated method MUST be able to work with seasonal variations (trees with no leaf cover ect) and for both broadleaf and conifers.
- Trees where 'speciesCommonName = Unknown' SHOULD BE evaluated if they are or not a tree. ALL data (regardless of species classification) needs to be evaluated 1 time by the algorithm.
- CHOOSE THE MOST POSITIVE USER EXPERIENCE for when to run the algorithm (this auto detection process should never slow down the loading and saving of data). If it is too burdensome to do this work on the front end then find a way to run this automation step on the backend (note: the changing/not changing of 'isValidated=SPAM' to 'isValidated=NEEDS VALIDATION' can take place at any point after the data has been saved by the user. It is our preference to run this process AFTER the user saves their data). 

Expected behavior:

- Create, modify, and test ML algorithm using the dev database credentials
- Once test passes, implement solution in production

Example images that ARE trees from the dev db:

(Conifer): /trees/1Br1HKUiEUxI47tVDMAv

https://firebasestorage.googleapis.com/v0/b/iseatree.appspot.com/o/trees%2F89ffc2bf-3e98-4c9f-8c9c-58fbda60e27a.jpg?alt=media&token=2b99d76b-1db5-4c85-a506-4e980b9f46be

(Conifer): /trees/xefEusfswPvMuSHW5po0

https://firebasestorage.googleapis.com/v0/b/iseatree.appspot.com/o/trees%2F103ac296-be35-49f5-bca2-56368ae1ebe2.jpg?alt=media&token=f2107bc0-949f-4f96-8c38-acd06bc87a6d

(Conifer): /trees/vOhheKbWoisG8qU1uIND

https://firebasestorage.googleapis.com/v0/b/iseatree.appspot.com/o/trees%2Fb7e67e51-8197-49ec-a0f1-9ab82d61d08a.jpg?alt=media&token=0efd88e5-4eab-4c51-aeb0-ef6a7af749f1

(Broadleaf): /trees/oJpSGhF6D0e1RlGnaY55

https://firebasestorage.googleapis.com/v0/b/iseatree.appspot.com/o/trees%2Fa343ec02-12de-40bb-8715-320eb7621d21.jpg?alt=media&token=f93b378c-0c35-4f75-8e00-8a73cfa064d3

Example images that ARE NOT trees from the dev db and need to remain 'isValidated=SPAM':

(Noble Fir): /trees/K3Ofgm0EoeaISfAVwqAI

https://firebasestorage.googleapis.com/v0/b/iseatree.appspot.com/o/trees%2F16388ada-db47-46c6-8668-b8f893d43841.jpg?alt=media&token=09fc0079-23a8-4ff2-842f-e4e9dd46bfe7

(Unknown): /trees/1xt91tGaoCLUyHHZlMJG

https://firebasestorage.googleapis.com/v0/b/iseatree.appspot.com/o/trees%2Fd63ef7b2-92c5-40dd-a4c2-7abed9307430.jpg?alt=media&token=4ec18700-9f36-4878-b086-566785a65bf7

(Sitka Spruce): /trees/KPJY7u30kp6UjWB4BqU0

https://firebasestorage.googleapis.com/v0/b/iseatree.appspot.com/o/trees%2Fa93d840d-fe30-4156-bbc7-733dad786364.jpg?alt=media&token=f7101f95-595c-4aac-9ab7-7951639ce456

(Incense Cedar): /trees/YPLhShjZXGHTWZhnHMPC

Example of what data is classified as when it is first entered into Firebase:

https://firebasestorage.googleapis.com/v0/b/iseatree.appspot.com/o/trees%2Fd2fbb2bd-f3bf-4ccf-9f93-8e1c55b9b120.jpg?alt=media&token=7870f29d-92f8-4c5b-a60d-b7fee88ab181
![isValidatedSpam](https://user-images.githubusercontent.com/62637055/170886029-5f4221be-5098-47be-ae53-e3ae73b0caf7.JPG)

Example of a entry that has been identified as a tree and has been promoted to  'isValidated=NEEDS VALIDATION' )

![isValidatedNeedsValidation](https://user-images.githubusercontent.com/62637055/170886086-62a801eb-a4b4-4f47-811c-dcf403a748d9.JPG)

Where to find the url in the database (where the images are):

![photo_url](https://user-images.githubusercontent.com/62637055/170886106-099b7d35-aa1f-4e41-8120-83ecc76e69ef.JPG)

**Comment by bestw07** [comment]
I checked this ticket with @TreeMama .

She wanted to update the 'isValidated=SPAM' field when we submit the tree information to the firebase.

Now, we have the firebase cloud trigger function already.

The ideal logic is to detect if it is a tree or not from the submitted image, but unfortunately, the firebase ML kit supports individual modules (like Android and iOS java/kotlin, or swift) only.

In other words, @TreeMama  and I wanted to detect it and update the 'isValidated' field using the firebase cloud trigger function.

So I did research on this feature and I found one article to detect the tree.

https://www.section.io/engineering-education/react-native-firebase-image-labeling/

If we get an image labeling response when we take a photo of the tree, then we can submit this information to the firebase collection.

That's all.

Hope it will be helpful for any other cooperator, thanks.

**Comment by TreeMama** [comment]
Marking this as complete as of the v4+ release. Team has been utilizing [Plant.ID](https://web.plant.id/plant-identification-api/) ([more background can be found here](https://github.com/TreeMama/iSeaTree-React-Prototype/issues/419)).

When a user uses 'TreeBot' - currently - if the object photographed is confirmed as 'isPlant' it will be saved directly as 'NEEDS_VALIDATION' (instead of as 'Spam').

More work still should be done to auto-reduce the amount of manual need for 'Spam' entries - but I will open tickets on these later.
