### ISSUE TITLE
V 3.+: (NEW FEATURE / ENHANCEMENT) Redesign the 'Info' menu with new search options and photo menu

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#302]
ToDO: Since the completion of #197 we now have a photo options for all the trees in the species.json. Time to update and integrate this feature into our 'Info' menu.

- [x] Design a mock up of the menu in Figma
- [x] Delete the existing 'Information' menu (and the 'i' icon) update with the tree icon (see Figma designs below)
- [x] (Backend) Create lists of items in python to find out what cases we need to finish the 'Genus' dataset. Query out from the species.json all the cases of 'spp.' in the "COMMON" field. These are Genus level entries. Compare them with a grouped list of the names in the "GENUS" field.
- [x] (Backend) for all cases where there is NOT a 'spp.'  entry for the Genus name - create a new entry in the species.json. Find at LEAST one image for this GENUS in the current EOL store (it is okay if it is the same image as another entry of that GENUS). Source this image in the "FULL_PIC" field. Fill out other necessary fields like "ITREECODE", "DESCRIPTION", "TYPE","COMMON","SCIENTIFIC" "ID", and "GENUS"
- [x] (Backend) Load images into github, resize, link the resized images in the species.json. Prep them for load into AWS & Load.
- [x]  (Front-end) create the 'Info' menu. Add the tree icon to the nav bar (if it is not already there)
- [x]  (Front-end & Backend) create the multi-filter options as seen in the menu below. Users should be able to sort alphabetically by either "COMMON" or "SCIENTIFIC" name. Menu can also open to display all the available species under 1 GENUS of tree. They also can see the difficulty ranking ("easy", "medium", "expert" from "LEVEL" field) of the tree by icon (icons are provided here: https://drive.google.com/drive/folders/1ZmumvGBYZWArgl49v6HwTXsNihXsnkd-?usp=sharing).
- [ ] (Front-end) User will be asked at the end menu for a species entry if they want to add this particular tree to the 'Add' menu. If they say 'No' the menu closes and goes back the previously opened menu. If they say 'Yes' they are taken to the 'Add' page and the 'Species' name is already filled out for them (see Figma examples below)

IMPORTANT:
- [ ] Fix 'More Tree info >'. Once ALL the above is complete, make sure the 'More Tree info >' option on the pop-ups on the 'Explore' page is now fully integrated with this new 'Info' menu (selecting 'More Tree info >' should open the species level menu (as shown in the graphic). 

![tree_info_fix](https://user-images.githubusercontent.com/62637055/202476680-613614cd-14ad-4bce-a9a7-608a704f50a3.png)

As of version 1 this 'More Tree info' has been hard coded to the few different pages available in the 'Information' menu. Now we will have information available on EVERY tree....except the 'Unknown'...so the expectation is this 'More Tree info >' menu option with be available for everything on the map.

Clicking on this:
![image0 (5)](https://user-images.githubusercontent.com/62637055/179850960-fe3a293a-3a5e-41fe-ba3f-a8e269e44a0a.png)

Should open this:
![image0 (6)](https://user-images.githubusercontent.com/62637055/179851407-814c5f7e-adfd-45d1-a81b-033c050da36e.png)

Figma design is here: https://www.figma.com/file/qPsbrgYovo3Tu7zgziql42/iSeaTree?node-id=2%3A1867

Icons are here: https://drive.google.com/drive/folders/1ZmumvGBYZWArgl49v6HwTXsNihXsnkd-?usp=sharing

Example of the main 'Info' menu and the alphabetical sorting and filtering options:
![1](https://user-images.githubusercontent.com/62637055/179849442-c5fadcb6-12ac-44fd-bfa3-258a155bd3e8.JPG)

Example of filtering/selecting a specific species by GENUS:
![select_via_genus](https://user-images.githubusercontent.com/62637055/179849462-aa3da83f-7ad3-41fc-b5cd-54381de7d7ae.JPG)

Example of selecting a specific species by SPECIES:
![select_via_species](https://user-images.githubusercontent.com/62637055/179849736-d0ec201b-fea3-43d5-a53e-9393795ebacf.JPG)

Example of going to the 'Add' menu from 'Info':
![selected_and_added](https://user-images.githubusercontent.com/62637055/179849781-705505b2-4d07-4085-a5be-69c9bfee2be8.JPG)

**Comment by TreeMama** [comment]
Christy H. Provided the below (the script is missing_genus_finder.py in the EOL images repo).

Here is a list of the genera (genuses?) that do not have their own instance (spp) in species.json:

['Unknown', 'Amelanchier', 'Arbutus', 'Asimina', 'Calocedrus', 'Carpinus', 'Cercis', 'Chamaecyparis', 'Cladrastis', 'Cornus', 'Corylus', 'Cotinus', 'Crataegus', 'Davidia', 'Eucommia', 'Fagus', 'Gingko', 'Gymnocladus', 'Halesia', 'Hamamelis', 'Koelreuteria', 'Lagerstroemia', 'Larix', 'Liquidambar', 'Liriodendron', 'Maackia', 'Malus', 'Metasequoia', 'Nothofagus', 'Nyssa', 'Ostrya', 'Oxydendrum', 'Parrotia', 'Phellodendron', 'Prunus', 'Pseudolarix', 'Pseudotsuga', 'Pterostyrax', 'Rhamnus', 'Robinia', 'Sciadopitys', 'Sequoiadendron', 'Sequoia', 'Sophora', 'Sorbus', 'Stewartia', 'Styrax', 'Taxus', 'Thuja', 'Tilia', 'Trachycarpus', 'Tsuga', 'Zelkova', 'Laburnum', 'Rhus', 'Juniperus', 'Ginkgoopsida', 'Quercus/live', 'Pittosporum', 'Pisonia', 'Prestoea', 'Arctostaphylos', 'Adonidia', 'Morus', 'Araucaria']

**Comment by TreeMama** [comment]
10/26/2022 update. I'm currently 1/3 of the way through the updates to add the genus for the species missing a genus entry.

**Comment by TreeMama** [comment]
@bestw07 

11/10/2022 update. All images and descriptions are complete for the next round of 'resizing' photos and adding them into AWS. 

The updates to the species.json are here (once the images are in AWS this species.json should be added into a new feature branch then pushed to /develop/  ONCE the AWS load is complete AND these rows are populated -   
     "FULL_PIC_180x110"
    "FULL_PIC_1024x768"
    "THUMB_PIC_1024x768"

https://github.com/TreeMama/iSeaTree_EOL_Images/blob/main/species.json

All NEW images are in this folder:

https://github.com/TreeMama/iSeaTree_EOL_Images/tree/main/missing_images_pt2

**Please note : SOME of the images in this photo are being added to entirely new json entries and SOME of the images are being added to existing json images.**

**Comment by bestw07** [comment]
we’ve made significant upgrades to the species.json. I have linked to new AWS images and Ari fixed the scientific names of all genus entries to include ‘spp.’

please use this species.json from the latest /develop/ to fix your genus filter menu issues Mohan and @ddwj
