### ISSUE TITLE
V 3.+: (BUG) UserName and Email on the Profile page doesn't appear

### ISSUE THREAD

**Issue by teressas** [TreeMama/iSeaTree-React-Prototype#304]
I downloaded the app last week and was able to see it at first, but then after closing the app and opening it back up, I'm not able to see the UserName and email anymore. I have an iPhone Xs Max, iOS 15.7.
Image of bug:
![IMG_9004](https://user-images.githubusercontent.com/91032459/194658001-31fe1345-e892-49c5-a814-6f0d6d2db211.PNG)

**Comment by TreeMama** [comment]
@teressas what device and OS are you using?

**Comment by teressas** [comment]
@mtalhadev Thanks for looking into the issue. I'm not able to repo this with my new account. I am going to close this ticket until I see it again.
