### ISSUE TITLE
V.3+ (CRITICAL BUG)  App freezes when user navigates away from it

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#306]
Version 3.0.6 (ios)

When user stops using app and goes to different apps (for a long stretch of time) the application frequently freezes and becomes unresponsive. Only way for user to 'unfreeze' is to delete the app and reinstall it.

ToDO: make sure the app status remains active and accessible EVEN when the user navigates away from the app.

https://user-images.githubusercontent.com/62637055/195475674-1c3ed355-f9f1-46b3-8f22-d2768fc78bc0.MOV

**Comment by queenieth** [comment]
Did not experience any freezes while navigating through the app

**Comment by queenieth** [comment]
https://user-images.githubusercontent.com/6989882/199072281-9cce9aee-b107-473c-afd8-f5748c4a5fd9.mp4

The app froze for a while after navigating out to other apps but after much clicking it finally responded.

**Comment by bestw07** [comment]
how much time did you put the iSeaTree app on background status, @queenieth ?

**Comment by queenieth** [comment]
@bestw07 I made different videos, some as  much as 4 mins but couldn't upload it coz of the size

**Comment by TreeMama** [comment]
@mtalhadev - I'm still seeing this happen in the recent testflight ios build. I found this stackoverflow solution...could you possibly try to implement it - see if it helps?

https://stackoverflow.com/questions/59280668/react-native-sometimes-app-freezes-when-opened-from-background

**Comment by TreeMama** [comment]
@mtalhadev I'm wondering if this might have anything to do with the fact we switched off expo a few years ago (and went for a pure react-native framework). Reading this made me wonder if the bug was somehow related to that

https://blog.expo.dev/how-to-run-background-tasks-in-react-native-e1619acef48f

**Comment by TreeMama** [comment]
I haven't seen this issue in the latest testflight build (4.0 / 67). I believe @mtalhadev has fully resolved it - thank you!
