### ISSUE TITLE
v 3+ (BUG) remove page names from top of screen

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#324]
ToDO: 

Need to remove words like 'profile' 'mapScreen' and 'addTree' from top of screen.

![remove navigation](https://user-images.githubusercontent.com/62637055/203467591-eb2fa0d5-ecf6-45ef-8eb5-7eb318e86c5c.JPG)

**Comment by bestw07** [comment]
Hi, @dddwj 

I updated species.json file at develop branch.

And removed label at the header.

You can pull develop branch on your machine.

thank you.
