### ISSUE TITLE
v 3+ Update all loading images for Android/IOS stores

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#326]
All images for the playstores need to be updated.

Here are our current (outdated repos for storing these images):

All existing resolutions / sizes / options must be replaced (at the same resolution/size)

Also review the specs here (thanks @halmueller )
 https://help.apple.com/app-store-connect/#/devd274dd925
Needed according to App Store Connect: 5.5" and 6.5" iPhone. 12.9" iPad Pro (2nd and 6th generation).

IOS
https://github.com/TreeMama/iSeaTree-React-Prototype/tree/develop/iOS%20screenshots

Android (with script)
https://github.com/TreeMama/iSeaTree-React-Prototype/tree/develop/Android%20screenshots
![image3](https://user-images.githubusercontent.com/62637055/203471606-167b0252-5e09-4c7a-96d4-b2b0b7974f50.png)

**Comment by halmueller** [comment]
I'll replace what's on the iOS App Store with the contents of the iOS Screenshots folder, following the models and sequence numbers. If there's an obsolete image or model, please delete.

**Comment by ASimmonsSteffen** [comment]
@halmueller they are all jpg's but I added the (photoshop) psd file to the repo too - just upload the jpgs. Let me know if you need anything else. Closing.

**Comment by TreeMama** [comment]
we will know for sure once we submit to app store - but at the moment @halmueller approved closing this issue.
