### ISSUE TITLE
v 3+ (BUG) Filter menu in the 'Info' page should be inside the search bar

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#334]
ToDO: Madison's[ Figma design](https://www.figma.com/file/qPsbrgYovo3Tu7zgziql42/iSeaTree?t=4rZjHo0xU9RXpN0l-0) has the filter options button inside the search bar. Is it still possible to put it there?

How Madison's design looks:

![filter](https://user-images.githubusercontent.com/62637055/204560529-86f11916-3ff7-4a44-8f51-df649209835f.JPG)

How it looks now (@bestw07 / @andaniel2029 -  @dddwj 's feature branch is feature/info-screen - but be careful he has some M-1 configurations in there you might not want) 👍 
![fix_error2](https://user-images.githubusercontent.com/62637055/204560725-63cec316-dbd5-4b12-b8e6-89c2b4a5b542.JPG)

**Comment by bestw07** [comment]
I fixed this ticket and pushed it on the feature/info-screen branch. I didn't change any M1 chip settings.

It all worked for me.

**Comment by dddwj** [comment]
Thank you @bestw07 ! That looks significantly better!! I will launch the PR soon for that branch.

**Comment by bestw07** [comment]
> Thank you @bestw07 ! That looks significantly better!! I will launch the PR soon for that branch.

you are welcome, @dddwj
