### ISSUE TITLE
v 3+ (Bug / formatting fix) Need to sync up the 'icon' designs from Info menu and the species menu (in Add Tree)

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#342]
ToDO: there are slight formatting differences in the implementation of the info menu and the species menu - specifically for this circled icon. Please sync the species menu design to what is in the info menu.

Also add more white space padding between the 'Close' button and the small species picture

![Capture1](https://user-images.githubusercontent.com/62637055/205805109-e756188d-4a6f-4af7-8639-5afddde71836.JPG)

ex of info menu
<img width="539" alt="screen_shot_2022-12-05_at_13 40 17" src="https://user-images.githubusercontent.com/62637055/205805169-0105bb01-b353-4395-a2a1-4c5f16858b3f.png">

**Comment by dddwj** [comment]
WIP. ETA: 12/6
