### ISSUE TITLE
v 3+ (BUG) Info Menu (also check the dialog from Explore - 'More Tree Info' )

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#343]
ToDO: some of our trees only have 1 photo - and that 1 photo will show up as a thumbnail AND as a full screen image. 

For this reason it is VERY important that ALL tree profiles open to this page with the 'FULL_PIC' as the first photo shown (in other words - FULL_PIC shows in both the small graphic next to the text on the lower left - AND as a full size pic in the screen. IF there are THUMB_PIC - they show up in a carasol behind the FULL_PIC. 

We must fix this before ship.

![northern_white_cedar](https://user-images.githubusercontent.com/62637055/205810637-13646b4d-7077-453b-98ad-ade3f96b3405.JPG)

**Comment by dddwj** [comment]
WIP. ETA: 12/6
