### ISSUE TITLE
v 3+ (BUG)  Need to fix the padding on the Calculated Tree Benefits page 

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#344]
ToDO: This is how it looks on the iPhone 13 simulator

Please add more white space/padding on the top so the words are clearly seen.

![bug_calculated_trees](https://user-images.githubusercontent.com/62637055/205811752-4611c637-f5aa-4380-8d38-1b988bb67809.png)

**Comment by bestw07** [comment]
Hi, @TreeMama .

I wonder where you get this screenshot.

When I tested it on develop branch and using my simulator, I didn't get a such issue.

Let me know the branch name and device specs, please.

thanks.

<img width="679" alt="Screen Shot 2022-12-08 at 05 06 49" src="https://user-images.githubusercontent.com/95283860/206354210-033d286b-5418-4da4-9f10-4df4c9c17d83.png">

**Comment by TreeMama** [comment]
@bestw07 I was on @dddwj 's branch - which is now merged into /develop/ . It was an IPhone 13 / ios 15.5 sim .

**Comment by dddwj** [comment]
Did some research on this issue. I found this is an M1 Mac specific issue that needs extra configuration for screen size. This is an issue introduced by different screen default settings between M1 and intel xcode / dependent packages, (which is vague and wired).  As we will not check in any m1 configs to the codebase, I do not anticipate to submit code changes for this issue.
