### ISSUE TITLE
v 3+ BUG The tutorial 'Skip' 'Done' is hidden due to the larger navbar 

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#347]
ToDO: The fix for #324 had an unintended regression in the tutorial. 

By removing the names at the top of the page (see below) - the spacing was messed up  - and the 'Skip' and 'Done' and carousal dots are covered by the nav bar on the bottom.

Need to fix ASAP.
![TheBug](https://user-images.githubusercontent.com/62637055/205809699-c45d8bb0-8a79-48bb-a6dc-f4340905e4a7.JPG)

**Comment by dddwj** [comment]
Validated on my laptop. It works perfectly fine!
