### ISSUE TITLE
v 4+ (ADDING API RESULTS to FIREBASE) API Note: Example of the Results JSON from PlantID API

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#419]
This is for future documentation.

Since v4+ iSeaTree will offer an AI-assist option (TreeBOT) which utilizes [Plant.ID](https://web.plant.id/plant-identification-api/).

[Plant.ID](https://web.plant.id/plant-identification-api/) documentation can be[ found here](https://github.com/flowerchecker/Plant-id-API/wiki).

This is an example of the API's response string when passing this[ image](https://www.fast-growing-trees.com/products/red-sunset-maple-tree?variant=30321030955060&utm_source=google&utm_medium=cpc&utm_campaign=PMax:%20(MT)%20-%20Smart%20Shopping%20-%20Shade%20Trees&utm_term=&gclid=Cj0KCQiA_bieBhDSARIsADU4zLcNIo7aN3x4L8ctiv9kIoWS9QvOjc3tSXa64zPZYzK2QVQvNAkHTToaAjwcEALw_wcB) to it. 

[notepad.pw](https://notepad.pw/Ao1wxm7pvrGRmMC4LJ22) formated JSON response.

Also this is a [video](https://twitter.com/TreeMamaSEA/status/1592891644613132289) taken of the initial implementation steps.

Attached is the same JSON file.
[json_response_PlantID.txt](https://github.com/TreeMama/iSeaTree-React-Prototype/files/10486126/json_response_PlantID.txt)

**Comment by dceu** [comment]
Format:
{ 
...tree,
"highest_probability" : "number",
"other_possibilities" : [{id, plantName, probability}, {}, {},...],

}

**Comment by dceu** [comment]
Capture of ai suggestions beyond the initial:
https://github.com/TreeMama/iSeaTree-React-Prototype/compare/develop...ai_data

**Comment by dceu** [comment]
Letting the captured elements live in state?
https://github.com/TreeMama/iSeaTree-React-Prototype/compare/develop...ai_data

**Comment by dceu** [comment]
Pass state variable to submitTreeData, let submitTreeData pass param to TreeData interface:
https://github.com/TreeMama/iSeaTree-React-Prototype/compare/develop...ai_data

(╯°□°）╯︵ ┻━┻

**Comment by TreeMama** [comment]
@dceu do you have a pull request for this?

 @bestw07 I think @jgrenadier  already looked a bit over this - but we do need a final CR of it - @dceu was wondering if there is a good time this week to meet maybe?

**Comment by jgrenadier** [comment]
Hi,

I dont think I looked at 419 but let me know how I can help.

Jim

**Comment by TreeMama** [comment]
There were some regressions in this PR. Looks like the edits Mony made for stuff like the stuff from #371 ...also as of the release Build 4.1.4 (81) the issue #454 is back.

**Comment by TreeMama** [comment]
Closing and reopening #454
