### ISSUE TITLE
My found tree count is zero

### ISSUE THREAD

**Issue by jgrenadier** [TreeMama/iSeaTree-React-Prototype#432]
Even though I have entered several trees, my count is still zero.
Version is the prerelease 4.0.5
![count_zero](https://user-images.githubusercontent.com/20176233/215290708-6b604411-817a-4918-b0de-71c053d87bf3.png)

**Comment by TreeMama** [comment]
Is it still zero @jgrenadier - I saw some of yours come through the validation process today. Can you check again?

**Comment by TreeMama** [comment]
Part of this looks to also be a lodgic problem - thrown by the new implementation of TreeBOT (which allows users to skip the SPAM -> NEEDS_VALIDATION manual check). I opened ticket #438 to deal with this. Great bug catch @jgrenadier (though - I fixed some of this temporarily in the db - you should NOT have a 0 count as of now 1/29/2023).

**Comment by TreeMama** [comment]
Closing because it is captured it ticket #438 now...
