### ISSUE TITLE
(NEEDS CODE REVIEW) if button takes awhile to change screen, no indicator shown to user

### ISSUE THREAD

**Issue by jgrenadier** [TreeMama/iSeaTree-React-Prototype#434]
For example, when showing the "explore tab" and then the user clicks on the "camera icon",
it takes multiple seconds for the camera entry tab to be visible.  The user gets no feedback
that the camera entry page is going to be make visible.  Hence, the user will click multiple
times or click on other buttons. This will probably slow down the app and leave the user
unhappy.
![takestoolong2](https://user-images.githubusercontent.com/20176233/215291723-34db90bd-68a0-43c6-841f-088bc4279c05.png)

This is using the prerelease 4.0.5 version

**Comment by jgrenadier** [comment]
I was sort of hoping someone would say this was a good idea or not to implement.  No word, so I'm going to try out using a progress bar described here: [](https://stackoverflow.com/questions/75008746/make-react-native-progress-bar-show-progress) 

using this code:
const styles = StyleSheet.create({
  container: {
    width: '100%',
    height: 10,
    backgroundColor: '#CCC',
    borderColor: '#0AF',
    borderWidth: 1.5,
    borderRadius: 3,
    overflow: 'hidden',
  },
  progress: {
    height: 10,
    backgroundColor: '#0AF',
  },
});

const ProgressBar = ({ progress }) => (
  <View style={styles.container>
    <View style={[styles.progress, { width: `${progress * 100}%`}] />
  </View>
);

.. and see if I can make it look reasonable.

**Comment by jgrenadier** [comment]
Tested with the latest android app and performance seems better and buttons change color when I click on them.  So maybe this change isnt necessary.  I'll try under different network conditions and see if I can reproduce an issue.  Otherwise, I'll close this for now,

**Comment by jgrenadier** [comment]
The performance (at least now) seems only to do with clicking on the camera icon on the main tabbed user interface.  It sometimes takes a very long time for the "Add a Tree" user interface to be visible and the focus color for the camera icon to change.  Sometimes it is fast and sometimes it takes close to forever.  I would at least like to see if there is a way to make the tabbed interface icon color change immediately.  The problem seems most related to switching from the "explore" map mode to the camera icon.

**Comment by jgrenadier** [comment]
a little knowledge is a dangerous thing. I wrapped the image for the AddTreeScreen in a View (similar to the other screens) and clicking on the camera icon is much more reliable.  code cleanup and some more research and I may have a fix.

**Comment by TreeMama** [comment]
reviewed with @jgrenadier AND @dceu ON 4/13
