### ISSUE TITLE
v4+ Tree Count doesn't increment correctly if user is using TreeBOT (FIREBASE)

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#438]
ToDO: the Legacy rules of our TreeCount (some of this was implemented in #55 and some of it was just carried over from the initial EXPO build) don't work well for our TreeBOT.

Under the current rules:

USERS ONLY GET  UPDATED 'treesCount' in Firebase IF they go from isValidated = SPAM to isValidated = NEEDS_VALIDATION

We still need to keep this rule - BUT we need to amend it to include the TreeBot lodgic (which if the user has TreeBot ON and takes a picture of something that is a plant - the entry NEVER is entered as SPAM but is entered as NEEDS_VALIDATION). 

The new rule should now include these two use cases:

1) USERS GET a +1 UPDATED in 'treesCount' in Firebase (on their 'users' table) IF they DO NOT USE TREEBOT (i.e. AIResult = 0) and go from isValidated = SPAM to isValidated = NEEDS VALIDATION

AND

2) USERS GET a +1 UPDATED in 'treesCount' in Firebase (on their 'users' table) IF they USE TREEBOT ((i.e. AIResult = 1) and the entry is isValidated = NEEDS VALIDATION

**Comment by jgrenadier** [comment]
I checked my tree count today:
Trees identified: 7
Badges Earned: 5.
So, the bug the bug seems to be fixed now.

**Comment by TreeMama** [comment]
Nah that was all me @jgrenadier ;) We've still got to fix the firebase function

**Comment by dceu** [comment]
https://github.com/TreeMama/iSeaTree_Firebase_Functions/pull/2

**Comment by TreeMama** [comment]
* Whoops needs to be 'NEEDS VALIDATION' (no '_'). @bestw07 
![erre](https://user-images.githubusercontent.com/62637055/221695789-268f6c6f-bf61-420d-b6bc-409ec4521a8e.JPG)

**Comment by TreeMama** [comment]
@dceu confirmed the fix in 4.0.8 / 75. Closing!
