### ISSUE TITLE
v 4+ Add 'Melia azedarach' (Chinaberry tree) along with 'Melia spp.' to species.json

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#439]
ToDO: @jgrenadier identified with TreeBot a Chinaberry tree (EGevfL08x5Hme2muqy3a). TreeBot called it a 'Box Elder' (Acer spp.). 

Need to add 'Melia azedarach' & 'Melia spp.'  to species.json then correct entry 'EGevfL08x5Hme2muqy3a' (01/28/2023).

This is the photo: https://firebasestorage.googleapis.com/v0/b/iseatree-dev.appspot.com/o/trees%2Fef0e064f-7587-4403-ac72-6f2b6fbf916c.jpg?alt=media&token=a98f7c45-d870-415f-ab7e-f16b29f47a7d

**Comment by TreeMama** [comment]
![chinaberry](https://user-images.githubusercontent.com/62637055/222628025-98e2076e-97bb-43e2-9348-6a2accc51d60.JPG)
![image1 (3)](https://user-images.githubusercontent.com/62637055/222628238-5d55d483-11ba-43df-afbb-058d80991ec2.png)
![image0 (24)](https://user-images.githubusercontent.com/62637055/222628241-fddffeae-211b-46f8-b461-7f5ae7a705a1.png)

**Comment by jgrenadier** [comment]
Tested with and without the bot and it works ok.  Tree count update took awhile but was ok too.

**Comment by TreeMama** [comment]
@jgrenadier - hey there if you get a chance can you use the app to try to update this tree from a 'Unknown' to a 'Chinaberry'? TO do this you use the Explore page. Press the text I have circled.

![222628241-fddffeae-211b-46f8-b461-7f5ae7a705a1](https://user-images.githubusercontent.com/62637055/223312082-037890ce-e5da-4067-83a3-77afc0bab20c.png)

Ari this is record 'EGevfL08x5Hme2muqy3a'

**Comment by jgrenadier** [comment]
validated the tree.
