### ISSUE TITLE
v 4+ Typo in Bald Cypress spp. Description

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#456]
ToDO:

![baldcypress](https://user-images.githubusercontent.com/62637055/222194522-60dfdb8f-ea4d-416a-9748-3abe6d87024a.png)

**Comment by jgrenadier** [comment]
looks like someone already updated species.json

**Comment by TreeMama** [comment]
Looks fixed in version 4.1.4 (82)
