### ISSUE TITLE
v 4+ (URGENT) intermittent error iTreeAPI appears to not be called (on the release build - 74)

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#467]
03/26/2023 - this error (see video) just started appearing with build 74. Oddly the same build was used earlier in the week - and there was no error - however we are noticing that iTreeAPI data is NOT getting saved to the backend and OCCASSIONALLY isn't showing up in the front end.

*UPDATE* on 03/27/2023 - this error seemed to disappear HOWEVER it was noticed that though the iTree API results were showing up on the frontend - but NOT being saved in the backend. 

After meeting with Mony (03/27/2023) we decided to NOT let the  'Success You have added a new tree successfully' message show if the user is still ON the 'Calculated Tree Benefits' page. 

ToDO:

Please make sure that the SAVE of the tree data to firebase and the 'Success You have added a new tree successfully' msg DO NOT TAKE PLACE UNTIL AFTER the user has selected 'DONE' on the  'Calculated Tree Benefits' page. 

Video: Shows the  'Success You have added a new tree successfully' immediately - with the same 'The USFS iTree API was not able to calculate the Tree Benefits for this tree'.

https://user-images.githubusercontent.com/62637055/227828212-fc0d820d-71b7-44d0-869e-b3b8def8aa98.MP4

**Comment by dceu** [comment]
getItreeData isn't called from the AddTreeScreen.tsx

**Comment by bestw07** [comment]
> 

`getItreeData` is for `MapScreen.tsx.`
