### ISSUE TITLE
v 4+ Fix leaf type in Sugar maple

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#482]
It is simple not bipinnate  (check all Sugar Maples - several are labelled wrong)

  {
    "COMMON": "Bonfire Sugar Maple",
    "TYPE": "broadleaf",
    "SCIENTIFIC": "Acer saccharum ‘Bonfire’",
    "ID": "26",
    "ITREECODE": "ACSA2",
    "LEVEL": "expert",
    "THUMB_PIC": "",
    "FULL_PIC": "/missing_images/26/plantstogrow/00001153_38680923900463Acer_saccharumBonifire-02cm.jpeg",
    "GENUS": "Acer",
    "BARK_TYPE": "",
    "LEAF_SHAPE": "",
    "LEAF_VEINS": "",
    "LEAF_EDGES": "",
    "LEAF_TYPE": "bipinnately compound",
    "TREE_SHAPE": "oval",
    "FRUIT_SEED": "",
    "BARK_COLOR": "",
    "LEAF_COLOR": "",
    "LEAF_ARRANGEMENT": "",
    "LEAF_UNDERSIDE_COLOR": "",
    "LEAF_TEXTURE": "",
    "DESCRIPTION": "The 'Bonfire' Sugar maple is a deciduous tree that has a broad oval form. Grows up to 50 ft high and 35 ft wide (15 m by 10 m); and is reportedly a rapid grower. Leaves are medium green in summer turning to yellow, orange, orange-red and red in fall. Color may very with site conditions.",
    "FULL_PIC_180x110": "new_images/26/plantstogrow/00001153_38680923900463Acer_saccharumBonifire-02cm_180x110.png",
    "FULL_PIC_1024x768": "new_images/26/plantstogrow/00001153_38680923900463Acer_saccharumBonifire-02cm_1024x768.png",
    "THUMB_PIC_1024x768": ""
  },

**Comment by jgrenadier** [comment]
fyi: to understand the issue better, I asked ChatGPT: 
"No, sugar maples (Acer saccharum) are not bipinnately compound. 
Bipinnately compound leaves have leaflets that are further divided 
into smaller leaflets, giving them a feathery or fern-like appearance. 
Sugar maples, on the other hand, have simple leaves with lobes that are not further divided. 
However, some other species of maples, 
such as the silver maple (Acer saccharinum), have bipinnately compound leaves."

**Comment by jgrenadier** [comment]
after a bit more googling, I confirmed that we need to have all these trees have a "simple" leaf type: 
bonfire sugar maple
commemorative sugar maple
mountain sugar maple
legacy sugar maple

and fyi: "freeman maple" ( hybrid of sugar and silver maple) already has a simple leaf type and that's ok.
and species.json has silver maple as a "" leaf type. Which is probably ok too.

**Comment by TreeMama** [comment]
Ah - ChatGPT....never know what its going to say next :P (I'm making fun of its take on the 'Silver Maple'). 

Everything maple is usually a 'simple' leaf type - with the grand exception of the Boxelder (#31) who is pinnately compound.

Thanks for leaving #366 (Silver Maple) blank - it is definitely 'simple' -  we will pick up that particular fix in the next iteration.

Since this was just a ticket for the Sugar Maples - I say good work job done!
