### ISSUE TITLE
v 4+ (URGENT) there are images not loading (Bradford Pear, Callery Pear, Dracaena spp., Citrus spp.)

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#495]
ToDO:

Tested on v 4.1.3 (Build 80) in testflight.

New(er) adds to the species.json are not showing images - maybe they didn't load to AWS? The particular ones I noticed missing are the 'Bradford Pear' and the 'Callery Pear'.

We need to resolve this BEFORE 6/7/2023.

**UPDATE (6/6) - I checked. All the missing images seem to be images that were in this folder (before the load to AWS):
https://github.com/TreeMama/iSeaTree_EOL_Images/tree/main/missing_images_pt4

With the exception of 392 (which I already removed and was fixed in 'missing_images_pt5') - all these images need to be resized and added to AWS.**

![image0](https://github.com/TreeMama/iSeaTree-React-Prototype/assets/62637055/8b1a10e6-688d-4065-a2cc-b1846afcdc4f)

**Comment by TreeMama** [comment]
Also noticed these 2 (who were added around the same time the Callery Pear was) are also missing images...
![image0 (1)](https://github.com/TreeMama/iSeaTree-React-Prototype/assets/62637055/bfc3375f-574a-4a0c-8c44-8baad7091b72)

**Comment by bestw07** [comment]
ok, I remove entire images in the aws s3 bucket.

I am uploading it again.

After uploading is done, all images should appear.
