### ISSUE TITLE
v 4+ (URGENT) The 'Add Tree' screen doesn't clear after user enters data

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#497]
ToDO:

'Add Tree' screen needs to reset/set all fields to blank AFTER a user has successfully added a tree.

Ari (on ios - build 80) saw the same behavior (of data still showing in the form after a successful data load). However, Ari did note that the 'Clear' button worked fine - and was still able to load a new tree after using the 'Clear' button.

Christy made this video using Android (v 4.1.3 build 80)

https://www.dropbox.com/s/qxf7gjr5zb02n8f/Video%20Jun%2005%202023%2C%208%2018%2034%20PM.mov?dl=0

**Comment by bestw07** [comment]
this issue is related to this commit.

https://github.com/TreeMama/iSeaTree-React-Prototype/commit/3fd752cf1f7c89c47c9c7efdefda15ba0a445938#diff-cd0a3fa111b3d4a599b47e646eb0520e33dc0b84f3905b4a2f8acec7c76ebcfc

**Comment by TreeMama** [comment]
Looks fixed in version 4.1.4 (82)
