### ISSUE TITLE
v 4+ 'Treebot Avatar' disappears after user 're-opens' the app

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#498]
ToDO:
This was found in (v.4+ build81) on a samsung s22 plus. The error is that once the user selects a avatar - the avatar does NOT reappear when the user reopens the app. 

Need to fix so that the avatar seed regenerates to the previously selected avatar when the user 're-opens' the app.

https://github.com/TreeMama/iSeaTree-React-Prototype/assets/62637055/7f2dd92d-7d42-4509-b6a8-cb04f480f915

**Comment by jgrenadier** [comment]
trouble reproducing the issue. Tried latest code with several emulators and real pixel 4. . Worked ok.  Created a new device based on closest skins from Samsung and android 12 and worked ok.  I'll deassign myself from this issue for now.

**Comment by TreeMama** [comment]
@jgrenadier thanks for looking at this - I took a closer look and realised that Hana here doesn't have an account name showing up on the profile page. My best guess is she deleted her account - and didn't make another one. So without the account - there is no where for the avatar seed to be saved (thus she'd be force to regenerate it...again and again ...because there is nowhere in the database for it to be saved).

![Account_name](https://github.com/TreeMama/iSeaTree-React-Prototype/assets/62637055/e11b107c-e8c6-4ff2-9284-de3d1266887e)

**Comment by TreeMama** [comment]
@jgrenadier I talked to Hana - she created a new account and the error did not repo. Closing.
