### ISSUE TITLE
v4+ Add Russian Olive/Water Oak/Catalpa spp/Tilia cordota/Quercus agrifolia

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#503]
See title above.

When Russian Olive is added - update entry 'uGr5b1ZdZcFZdLIWoxLE' (taken January 28, 2023, 1:13:40 PM)

**Comment by TreeMama** [comment]
@bestw07 the images and updated text are all in 'iSeaTree_EOL_Images' repo - ready for resizing and adding to AWS.

Once that is done the updates species.json needs to be added to this repo.

the image repo is: https://github.com/TreeMama/iSeaTree_EOL_Images/tree/main/missing_images_pt6

species.json is: https://github.com/TreeMama/iSeaTree_EOL_Images/blob/main/species.json

Please note there are 3 folders of images (12, 251, 306) which are being ADDED to the existing inventory of images for these species. WE DO NOT want to delete images for species # 12, 251, or 306 - we merely want to add to them.

**Comment by bestw07** [comment]
Hi, @TreeMama 

I have uploaded the images to aws S3 and updated the species.json file.

Here is PR.

https://github.com/TreeMama/iSeaTree-React-Prototype/pull/521
