### ISSUE TITLE
v 4+ 'SciStarter' logo is clipped - use different logo

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#508]
Tested v 4.1.6 (84) on an iphone 6 and noticed the scistarter logo is clipped. Needs to be moved further away from the right margin and probably should swap out with the below logo (not this screen capture).

![clipe](https://github.com/TreeMama/iSeaTree-React-Prototype/assets/62637055/a35e7351-3c69-4ae8-a80a-ee876705f3c1)

I recommend we try using this attached logo. (from Caroline on g-drive here: https://drive.google.com/drive/folders/1_T8gpsdp2ipzxbBo-gmdA33oKQ9POPYq). Also attached below
[SciStarter_logo_white_tag.pdf](https://github.com/TreeMama/iSeaTree-React-Prototype/files/12152429/SciStarter_logo_white_tag.pdf)

**Comment by bestw07** [comment]
Hi, @TreeMama 

There are so many logo files in your G-drive link.

Which file should I use exactly? lol

**Comment by TreeMama** [comment]
@bestw07 can you use the pdf attached in the ticket? 

https://github.com/TreeMama/iSeaTree-React-Prototype/files/12152429/SciStarter_logo_white_tag.pdf

**Comment by bestw07** [comment]
no, I can't. I need .png format file.

**Comment by TreeMama** [comment]
ok @bestw07 - does this work?
![SciStarter_logo_white_tag@1000px](https://github.com/TreeMama/iSeaTree-React-Prototype/assets/62637055/f104f48e-bcd6-40e1-8d87-a30cdb844387)

**Comment by bestw07** [comment]
bottom letters don't appear, because that has white color.

<img width="602" alt="Screenshot 2023-07-25 at 16 34 35" src="https://github.com/TreeMama/iSeaTree-React-Prototype/assets/95283860/8a3b56c1-d130-41a2-91b6-1683fddb1c49">

**Comment by TreeMama** [comment]
@bestw07 ok - well I don't want the bottom letters to appear - they are too small to read anyway. 

I cropped the png - does this work better? Also - can we MOVE the logo more left?
![cropped](https://github.com/TreeMama/iSeaTree-React-Prototype/assets/62637055/493d2c30-e316-484a-8c19-81fa49395bcf)

**Comment by bestw07** [comment]
<img width="602" alt="Screenshot 2023-07-25 at 17 04 18" src="https://github.com/TreeMama/iSeaTree-React-Prototype/assets/95283860/d772530e-72e5-486d-bf77-2efb7daf71a6">

**Comment by TreeMama** [comment]
@bestw07 the iTree logo is still a bit small...if you could make it a touch bigger than we are probably good.

**Comment by bestw07** [comment]
<img width="602" alt="Screenshot 2023-07-25 at 17 10 26" src="https://github.com/TreeMama/iSeaTree-React-Prototype/assets/95283860/d40208da-429c-4a15-aeae-bc008b367425">

**Comment by TreeMama** [comment]
@bestw07 haha well that's a little too big - is there a size between that (and the smaller one)?

**Comment by bestw07** [comment]
<img width="602" alt="Screenshot 2023-07-25 at 17 11 50" src="https://github.com/TreeMama/iSeaTree-React-Prototype/assets/95283860/a33c70f9-725d-4a97-aef7-0f718093722b">

**Comment by TreeMama** [comment]
ok just go with the bigger one. It's the only one I can read without glasses (the one you showed before this last one).
<img width="602" alt="255946105-d40208da-429c-4a15-aeae-bc008b367425 (1)" src="https://github.com/TreeMama/iSeaTree-React-Prototype/assets/62637055/b68714c1-fa12-4c69-a516-8a366003e743">

**Comment by bestw07** [comment]
ok Lol :)

**Comment by TreeMama** [comment]
closing
