### ISSUE TITLE
V 1.03: Grammar Typo

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#51]
Small grammar errors in the "You've found" message....can we fix? Watch out on spacing....

@prasanna-dhamodaran 
![prob](https://user-images.githubusercontent.com/62637055/89253421-7e2d4a80-d5d1-11ea-8dff-b8a94befd7f8.JPG)

**Comment by JonathanKoerber** [comment]
Issue closed with merge #86

**Comment by TreeMama** [comment]
Confirmed in 1.1 release thanks @JonathanKoerber !
