### ISSUE TITLE
v 4+ Make the percentage value on the 'TreeBot' match make sense...and fix spacing

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#518]
ToDO:

Currently the percentage value is being presented erroneously. It should be either a decimal value OR a percent value (cannot be both).

Please change this to read '99%' rather than '0.99%'.

Also there are some spacing issues in this message. I would REMOVE the spaces I've underlined in red (it is the space between the # and the '%') AND add a space between the '.' and the 'With' (see underline in blue).
![AI_underlined](https://github.com/TreeMama/iSeaTree-React-Prototype/assets/62637055/3faca404-4a9a-4638-ad7e-20408e3d7031)

**Comment by jgrenadier** [comment]
Have a fix ready but will wait till fter issue 517 is deleased to develop.  Proposed text example:
![image](https://github.com/TreeMama/iSeaTree-React-Prototype/assets/20176233/8f237718-3f7f-4317-a972-b13ded6e964d)

**Comment by TreeMama** [comment]
Hey @jgrenadier - was this also in PR #519 ? I think we are getting close to a release - @bestw07  can you take a look (also I think this pr is behind the current /develop/ we might need to sync) - we need to make sure @kafkakk 's changes and @jgrenadier 's are all in develop without a regression

**Comment by jgrenadier** [comment]
It's not in 519.  I was just planning to release a pr  for this after 519 is accepted into deveop but if 519 is still open, I guess I can include this fix in it. More later.

**Comment by bestw07** [comment]
this change is not in #519.

I think we can make this change after all PR approves, @TreeMama .

Did you take a look @kafkakk 's PR?

**Comment by jgrenadier** [comment]
I tried to test pr 522 from @kafkakk but had trouble with no map being visible and exception when trying to add tree. Probably something wrong with my environment. Doesnt seem related to that code change. I'll try to investigate some.

**Comment by jgrenadier** [comment]
Given problem here, you might want to have someone else try to test 522.

**Comment by TreeMama** [comment]
closing.
