### ISSUE TITLE
4.2+: TreeBOT values that are 0% match AND probability entries in 'other_ai'

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#538]
This looks like it is likely tied to the work done for issue #517 . There are 2 items to address in this ticket.

These screenshots are from Build 89/v 4.1.7. (9/5/2023)

1) that TreeBot sometimes comes back with a "0%" success rating. This feels like it could possibly be a rounding error? This is what it looks like in the front end.

![image0 (2)](https://github.com/TreeMama/iSeaTree-React-Prototype/assets/62637055/ae5f1b99-d126-48d0-9f4c-921d67571f26)

This is what it looks like in the database.

![database](https://github.com/TreeMama/iSeaTree-React-Prototype/assets/62637055/cb08d09f-2aa8-4bf6-92df-4152171a0e2f)

2) It looks like the entries being added in the database are being duplicated (both the scientific AND common name are being entered). Ideally we would JUST want the scientific name being saved. Also - we'd like the 'probability' value saved to be shown as a decimal (this is how @dceu entered it for the other_ai values). Right now it looks like the number is being rounded to an integer - 1. 

We would really benefit having:

1)  JUST the scientific name and the raw (unrounded) decimal value of the 'winning' match entered.
2)  DO NOT enter anything for the common name. just have 1 entry (and it has the scientific name and probability as a decimal).

![database](https://github.com/TreeMama/iSeaTree-React-Prototype/assets/62637055/93d94764-f853-492b-aa26-4f91ab9f0ca1)

**Comment by TreeMama** [comment]
Hey @bestw07 I don't suppose you have a minute to check this out?

**Comment by bestw07** [comment]
Hi, @TreeMama 

I am checking it.

**Comment by bestw07** [comment]
I fixed the confidence number issue.

![Screenshot_2023-09-20-23-02-54-24_fa96579ccbffecdc18de2fe8ee545f71](https://github.com/TreeMama/iSeaTree-React-Prototype/assets/95283860/4f38370d-f2c0-48f8-80d5-c183b7daec15)

**Comment by bestw07** [comment]
firebase tree document

<img width="902" alt="image" src="https://github.com/TreeMama/iSeaTree-React-Prototype/assets/95283860/321cadf0-ecb5-4925-9119-d7a2093b058b">

**Comment by TreeMama** [comment]
Hi @bestw07 - Christy checked this with the live build today (90 - Android) and it looks like the probability number is still being rounded to a 1 (I was expecting to see a decimal).

@christyheaton do you remember what the front-end displayed (as a percent of match) when you entered these trees on 9/21/23?
![still_error](https://github.com/TreeMama/iSeaTree-React-Prototype/assets/62637055/25f5ee4e-b9be-429b-88e5-153e9f00229f)

**Comment by TreeMama** [comment]
closing! Looks fixed as of version 4.1.8/4.1.9
