### ISSUE TITLE
v4+ When user FIRST opens the 'Add' page have an alert that reminds them to turn on TreeBot if they need help identifying a species

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#544]
ToDO:

Right now users seem to be missing turning on 'TreeBot' when they need species identification assistance. 

To rectify this - when user FIRST (**and ONLY on the first time the user EVER goes to the 'Add' page**) have this pop-up OPEN when the user opens the 'Add' page.

Use the Robot graphic in this alert.
![robot](https://github.com/TreeMama/iSeaTree-React-Prototype/assets/62637055/773a6bcd-3a91-41ca-82f4-0396bc77dd52)

This popup should show up ONLY on the VERY FIRST time the user see's the 'Add" page. Otherwise the user needs to click on the '?' to open it.

**Comment by bestw07** [comment]
fixed.

https://github.com/TreeMama/iSeaTree-React-Prototype/pull/547
