### ISSUE TITLE
v4+ Make 'multi-user' map center on the North America/USA continent on initial load

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#545]
ToDO:

Right now when you open the map page - on multiuser - it initially centers on the Pacific Ocean. As seen in this video:

https://github.com/TreeMama/iSeaTree-React-Prototype/assets/62637055/8de46e9d-89c5-4687-8e82-b9b4095bd6df

Please have this initial load always center on geographic center of the USA:

 
The GEOGRAPHIC CENTER of the UNITED STATES
LAT. 39°50' LONG. −98°35'

**Comment by bestw07** [comment]
fixed it. @TreeMama needs to approve this PR.

https://github.com/TreeMama/iSeaTree-React-Prototype/pull/546
