### ISSUE TITLE
v4+ Avatar is missing

### ISSUE THREAD

**Issue by asimmonsAF** [TreeMama/iSeaTree-React-Prototype#548]
Repo'd on build version 89 on ios.

The avatar seems to be missing and not refreshing. 

![image0 (4)](https://github.com/TreeMama/iSeaTree-React-Prototype/assets/146278369/661c7266-40a5-4188-b21c-fc20ce0836c9)

**Comment by asimmonsAF** [comment]
Update looks like the API is down - tested with @bestw07 . https://www.dicebear.com/styles/bottts/#details

Left this message to the creator (on his Twitter page)
Hi Pablo! Our small hackathon OS group has been a big fan of your robot api - but we noticed this week that it seems down. https://www.dicebear.com/styles/bottts/#details It is only returning right now the default image. https://api.dicebear.com/avatar.png . Do you know if it will go back up? We really loved it - as did the kids using it!

**Comment by TreeMama** [comment]
I noticed this seems to be offered. Maybe the original is now deprecated?

https://www.dicebear.com/styles/bottts-neutral/

**Comment by FlorianKoerner** [comment]
https://github.com/orgs/dicebear/discussions/374

bottts works, if you use the correct url. 😊

**Comment by FlorianKoerner** [comment]
```js
function getAvatarUrl(seed: string): Promise<string> {
// return `https://avatars.dicebear.com/api/bottts/${seed}.png`
  return axios.get(`https://api.dicebear.com/7.x/bottts/svg?seed=${seed}`).then((res) => {
    return res.dat
  })
}


```

**Comment by bestw07** [comment]
@FlorianKoerner , I implemented it already and tested with @TreeMama .

thx.

**Comment by FlorianKoerner** [comment]
> I noticed this seems to be offered. Maybe the original is now deprecated?
> 
> https://www.dicebear.com/styles/bottts-neutral/

Just wanted to clarify that bottts is not deprecated. Both avatar styles (bottts and bottts-neutral) work 😊.

If you have any questions about dicebear feel free to contact me.
