### ISSUE TITLE
V2 : Add a TOTAL COUNT on the profile page of the app that shows "## trees recorded"

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#55]
Add a count that shows on the profile page - underneath the profile picture- and reloads everytime the app is relaunched that says:

"Welcome back! We have ## trees recorded - ready to add some more?"

**Comment by TreeMama** [comment]
@prasanna-dhamodaran

**Comment by halmueller** [comment]
I don’t think this should be a pop up. 

Put it on the opening screen with the badges. 

An app that shows me unnecessary and unsolicited pop ups gets deleted from my phone pretty quickly. Let me use the app. Show me information. But don’t interrupt me with a pop up that I am forced to acknowledge. 

Hal Mueller 
halmueller@gmail.com

**Comment by JonathanKoerber** [comment]
It looks like this issue has been open for a while. I thought that I could try and start working on a solution.

**Comment by halmueller** [comment]
If it’s a pop up, I call this an anti-feature. We aren’t collecting any useful information from the observer (answer options would be “yes, that’s why I opened the app” or “no, I didn’t really mean to open the app”). Popup creates needless friction for the observer. 

Hal Mueller 
halmueller@gmail.com

**Comment by JonathanKoerber** [comment]
@halmueller  @TreeMama I just pushed a branch featureTreesRecorded that adds the number of trees or text if their number is undefined. I don't have any trees so on my account it returns undefined I am curious to hear what your returns.

**Comment by TreeMama** [comment]
@JonathanKoerber I checked it out and I think it's awesome start. 

Some things I noticed. 

My 'treemama2' account has 7  badges - and they are causing a problem. Have to scroll pretty far down to see the treesCount value. 

I think we definitely need to move this number towards the top...right under the profile pic...maybe where we have the 'to help' 'to map' text. 

Is that possible?

![image1 (5)](https://user-images.githubusercontent.com/62637055/102000745-5f397600-3c9f-11eb-94a8-2d000b41d209.png)

**Comment by JonathanKoerber** [comment]
Ok I can move it up.

**Comment by JonathanKoerber** [comment]
it's moved!

**Comment by halmueller** [comment]
I think you’d have a better look with count and explanation on the same line and same font size. 

Two more points while you’re here:

The text for the map and forum links is tiny. Pretend you have 50 year old eyeballs. And light blue text on white isn’t very readable in bright sunshine. 

This screen is also a good spot to show (at the bottom) the version and build numbers. With both beta and production versions on the street, knowing what build you have is helpful. Right now we have users with 1.2(26), 1.2(25), and 1.1(20-something) on the street.

**Comment by TreeMama** [comment]
@halmueller I think this specific ticket is done, there is some formatting work to still do *as you note* I'll open a separate issue for it. Thanks so much @JonathanKoerber !
