### ISSUE TITLE
V2.5: Change from EXPO Camera Component to React-Native Camera Component (?)

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#63]
@prasanna-dhamodaran / @halmueller

**Comment by JonathanKoerber** [comment]
@TreeMama I can start looking at this one. Is there a reason that we're moving away from EXPO Camera?

**Comment by TreeMama** [comment]
@JonathanKoerber the background story on this one starts here.
https://github.com/TreeMama/iSeaTree-React-Prototype/issues/49

There was a case awhile back where *certain* android users were taking pictures and having them rotated after they captured the image. @prasanna-dhamodaran patched this error by applying another rotation (to get the image to load properly) - however when he did that - he reported that we should probably look into changing the  camera component.

**Comment by TreeMama** [comment]
Looks fixed in Build #53 (where we removed all expo components). Launch 2.1
