### ISSUE TITLE
V2.0.2: Create a tutorial screen

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#67]
Too many people do not know what to do / where they are when the app opens. Need to make this more intuitive. Javansir suggests a tutorial entry point when users first start with the app.

https://blog.tubikstudio.com/onboarding-tutorial-design-greet-inform-engage/

**Comment by ryanflynndev** [comment]
https://www.npmjs.com/package/react-native-onboarding-swiper

We could probably use this.

**Comment by TreeMama** [comment]
@ryanflynndev  here is a rough draft of the storyboard...do you think that swiper can help us?
[iSeaTree_Walkthrough.pdf](https://github.com/TreeMama/iSeaTree-React-Prototype/files/6087981/iSeaTree_Walkthrough.pdf)

**Comment by kailynnelson** [comment]
I can take a whack at this! 🌳

**Comment by JonathanKoerber** [comment]
There was some install issue with https://github.com/jacse/react-native-app-intro-slider. Here is another package which may work https://github.com/jacse/react-native-app-intro-slider

**Comment by czhou578** [comment]
I personally think that the compass (which you can click on to find the tutorial) should be placed in one of the last slides. The first few slides should be strictly focused on educating the user.

**Comment by czhou578** [comment]
![IMG_20210515_110633](https://user-images.githubusercontent.com/42430035/118373908-09c70500-b56e-11eb-8485-9f08b159feed.jpg)

Here are some of my ideas. Minor changes.

Enjoy!

Colin Zhou

**Comment by czhou578** [comment]
I also have left a folder called TutorialPics in the asset folder that has the designs which might be useful for the tutorial pages.

**Comment by TreeMama** [comment]
Follow up (5/27): drafted some text for what to do following Colin's design:

for graphic 1 (see the assets folder) the text should read: 

"iSeaTree is an app that allows you to identify and learn about different tree species in the US and Canada!"

for graphic 2 the text should read: 

"Your profile page will contain the number of trees you found, and the badges you have earned."

for graphic 3 DRAW a red arrow pointing at the single person selector graphic in the map. the text should read:

"The 'Explore' map page shows trees that you have entered, as well as trees that others have entered. 
Currently the map view is set to ONLY show the trees that you have entered. Change to the multiperson view  
to show trees that other people have entered."

for graphic 7 the text should read:

"On the 'Explore' page you can also help with validating 'Unknown' tree entries to make our data even better!"

 for graphic 8 the text should read :

"The "Add new" page is where you load new tree data."

for graphic 11v2 EDIT the lines "Total CO Storage Value" and "Total CO Storage" to read "Total CO2 Storage Value" and "Total CO2 Storage". Also add the following text:

"After you add new tree data to the "Add new" page you will be able to calculate the 'Tree Benefits" of your data entry for others to learn about!"

**Comment by TreeMama** [comment]
Dev notes:

this tutorial should OPEN every time a NEW version of the app is downloaded and opened. Also - there should be a small compass icon (see Colin's notes - last picture) on the Profile page where the user can reopen the tutorial if need be...

Also - following @JonathanKoerber 's advice - try this for the slider:
 
https://github.com/jacse/react-native-app-intro-slider

**Comment by TreeMama** [comment]
note: @monikap0612 - can you also add the last graphic and text? from above:

Final graphic should be the profile screen.

with (have a red arrow pointing) to the small compass icon. The text should read:

**Find & replay this tutorial using this icon!**

**Comment by TreeMama** [comment]
tested and released in v 2.0.2. closing!
