### ISSUE TITLE
Keyboard covers the "Create Account" button

### ISSUE THREAD

**Issue by michaelkirk** [TreeMama/iSeaTree-React-Prototype#68]
I had trouble figuring out how to create an account for my initial usage on iOS.

Upon first launch, I didn't immediately see the "Create New Account" button, instead I tapped into the "Email" field.

This popped the keyboard up, which covered and hid the "Create New Account" button.

Once the keyboard is popped, there is seemingly no way to dismiss it. So I didn't even realize there was a "Create New Account" button until I killed and restarted the app.
![login_obscured mp4](https://user-images.githubusercontent.com/217057/93001798-758c3600-f4e6-11ea-8948-cd34230f2ed6.gif)

Indeed it was my error, but it would be nice to help twitchy-tappy people like me recover from their mistakes.

Some suggested improvements might be:

- adjust the position of the button so that it rises with the keyboard to remain visible
- offer a way to dismiss the keyboard

**Comment by TreeMama** [comment]
closing
