### ISSUE TITLE
Invariant Violation: "main" has not been registered

### ISSUE THREAD

**Issue by blahutkam** [TreeMama/iSeaTree-React-Prototype#71]
This can happen if: Metro (the local dev server) is run from the wrong folder
![Screen Shot 2020-09-12 at 12 50 31 AM](https://user-images.githubusercontent.com/45284693/93003965-e720b000-f4f7-11ea-8d94-a80695f4abde.png)

**Comment by blahutkam** [comment]
Issue: mismatch in package.json

solution: 
1. checkout 'modified packages'
2. run 'yarn install' again

**Comment by halmueller** [comment]
To do: capture this info in README.
