### ISSUE TITLE
V2 - Need to be able to give users more options for location (for the tree benefits API)

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#74]
User case: We have a Snohomish Co. Teacher really interested in using the tool. This adjustment would make a BIG deal to her class and get us brainstorming about future improvements. 

Currently (9/19) the envVariables.ts is being used to hard code some iTree API stuff.

One part of this we need to give the user power to switch between.

ToDo:

A) There should be a way to use React-native-geocoding & react-native-geolocation to populate CITY  (note shouldn't this be COUNTY?) and CITYNAME and STATE and NATION

1)
export const CONFIG = {
 ITREE_KEY:
 API_TREE_BENEFIT:
 NATION: ‘United+States+of+America’,
 STATE: ‘WA’,
 CITY: ‘King’,
 CITYNAME: ‘Seattle’,
}

2) 
export const CONFIG = {
 ITREE_KEY:
 API_TREE_BENEFIT:
 NATION: ‘United+States+of+America’,
 STATE: ‘WA’,
 CITY: ‘Snohomish’,
 CITYNAME: ‘Edmonds’,
}

B) When the user first hits 'Calculate Tree Benefits' have a pop-up appear that asks them which COUNTY they are in (do not mention CITY) - Snohomish or King.  After they select one - the proper config file option should be added and the API for that region should be calculated accordingly.

**Comment by TreeMama** [comment]
@jeremydavidson notes; "React Native recommends this package: react-native-geolocation. Then, another package can translate coordinates to city: react-native-geocoding."

**Comment by JonathanKoerber** [comment]
I'm halfway on this one. I've taken the coordinates and returned an address using the expo-location package. I didn't use the react-native route because it requires a google account and API key. If I can get an API key then I can implement it.

**Comment by TreeMama** [comment]
@JonathanKoerber has knocked this one out of the park. Onwards to device testing!
