### ISSUE TITLE
V2 - Shagbark Hickory on 'Suggested' needs to be identified as 'easy'

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#76]
Need to change this (McBride's updates to the species.json updated it):

![update_shagbark](https://user-images.githubusercontent.com/62637055/94958387-4a24b780-04a4-11eb-8fa9-a64c3a9a2292.JPG)

**Comment by jyang81** [comment]
What does the levelText need to say? (The part that says "Expert, very rare in Seattle region. Non-native.")

**Comment by TreeMama** [comment]
The only text you should be worried about is that "Expert, very rare..." text. It has to be manually changed (the other one in the pill is already fixed). 

Should say "Easy" where it now says "Expert".

**Comment by jyang81** [comment]
Just checking. Wasn't sure if there were easy and very rare trees... I thought the whole line had to be changed.
