### ISSUE TITLE
V2- NEED to change text in the 'Calculated Tree Benefits'

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#79]
Thanks to @jeremydavidson  we now have a working CalculatedTree Benefits calculator.

Need to fix the CSS here to say:

"Tree Benefits are calculated using the 'iTree API' with permission from the USDS Us Forest Service."
![calculated_tree](https://user-images.githubusercontent.com/62637055/99885326-dae85b80-2be8-11eb-9d8f-c74253a6b3bd.png)

**Comment by jyang81** [comment]
Updated text and merged changes. Just need someone to confirm change has been properly made (I couldn't run the build at the time).
