### ISSUE TITLE
V2 - Return the values from iTree to Firebase

### ISSUE THREAD

**Issue by TreeMama** [TreeMama/iSeaTree-React-Prototype#94]
Use Case:

IF values are generated successfully from iTree - save them to Firebase when the user selects "SAVE".

**Comment by TreeMama** [comment]
Values we NEED to save to firebase are (in the iTree API XML..you can use the same naming convention in firebase - though I would make the FIRST letter lowercase):

1. <RunoffAvoided></RunoffAvoided> 
(* we convert to gallons, iTree API saves it as cubic meter - would be better to save it as gallons)

2.<RunoffAvoidedValue></RunoffAvoidedValue>

3. <CORemoved></CORemoved>
4. <CORemovedValue></CORemovedValue>
5. <NO2Removed></NO2Removed>
6. <NO2RemovedValue></NO2RemovedValue>
7. <SO2Removed></SO2Removed>
8. <SO2RemovedValue></SO2RemovedValue>
9. <O3Removed></O3Removed>
10. <O3RemovedValue></O3RemovedValue>
11. <PM25Removed></PM25Removed>
12. <PM25RemovedValue></PM25RemovedValue>

13. <CO2Sequestered></CO2Sequestered>
14. <CO2SequesteredValue></CO2SequesteredValue>

15. <CarbonDioxideStorage></CarbonDioxideStorage>
16. <CarbonDioxideStorageValue></CarbonDioxideStorageValue>

17. <CalculatedCrownHeightMeter></CalculatedCrownHeightMeter>
18. <CalculatedCrownWidthMeter></CalculatedCrownWidthMeter>

**Comment by sorratanak** [comment]
Return the values from iTree to Firebase #94 done

**Comment by TreeMama** [comment]
@sorratanak close - but we actually need to save more from the API then what the 'Tree Benefits Calculator' displays. There also seems to be an error happening with 'RunoffAvoided'... We need ALL The values from the xml tags listed above individually saved in Firebase.

For example, we don't need 'AirPollutionRemoved'  'AirPollutionRemovedValue' - but we do need all the data that makes that field (in the front end): 

3. <CORemoved></CORemoved>
4. <CORemovedValue></CORemovedValue>
5. <NO2Removed></NO2Removed>
6. <NO2RemovedValue></NO2RemovedValue>
7. <SO2Removed></SO2Removed>
8. <SO2RemovedValue></SO2RemovedValue>
9. <O3Removed></O3Removed>
10. <O3RemovedValue></O3RemovedValue>
11. <PM25Removed></PM25Removed>
12. <PM25RemovedValue></PM25RemovedValue>

Can you help with this?

**Comment by sorratanak** [comment]
Yes, No problem. I did. Please check the video and GitHub codes.
https://reccloud.com/u/ig8jzxw

**Comment by sorratanak** [comment]
Hello, @TreeMama .

I am Lenh.

Can you share your contact information please?

my email address is sorratanak@gmail.com.

Hope your reply soon. thank you.
